import React, { useState, useEffect, useMemo } from 'react';
import { 
  ArrowRight, Layers, CheckCircle2, BookOpen,
  Play, Pause, Square, FastForward, Rewind,
  ChevronRight
} from 'lucide-react';

interface ElementNode {
  id: string;
  label: string;
}

interface TourStop {
  id: number;
  title: string;
  subtitle: string;
  text: string;
}

interface SpokenWord {
  text: string;
  start: number;
  end: number;
}

let activeUtteranceRef: SpeechSynthesisUtterance | null = null;

export default function AdjunctionVisualizer({ language }: { language: 'en' | 'ja' }) {
  const getInitialRoom = (): number => {
    if (typeof window !== 'undefined') {
      const params = new URLSearchParams(window.location.search);
      const room = parseInt(params.get('room') || '1', 10);
      return (room >= 1 && room <= 10) ? room : 1;
    }
    return 1;
  };

  const [currentStop, setCurrentStop] = useState<number>(getInitialRoom);

  // Synchronize room state with URL query parameter
  useEffect(() => {
    if (typeof window !== 'undefined') {
      const params = new URLSearchParams(window.location.search);
      if (params.get('room') !== currentStop.toString()) {
        params.set('room', currentStop.toString());
        const newUrl = `${window.location.pathname}?${params.toString()}${window.location.hash}`;
        window.history.replaceState({}, '', newUrl);
      }
    }
  }, [currentStop]);

  const [setElements, setSetElements] = useState<ElementNode[]>([
    { id: '1', label: 'I' },
    { id: '2', label: 'I' },
    { id: '3', label: 'I' }
  ]);
  const [monoidWords, setMonoidWords] = useState<string[]>([]);
  const [animationState, setAnimationState] = useState<'idle' | 'free' | 'forget' | 'unit' | 'counit'>('idle');
  const [counitInput, setCounitInput] = useState<string>('I-I-I');
  const [counitResult, setCounitResult] = useState<string | null>(null);

  const tabContent = useMemo(() => {
    return {
      en: {
        narrative: "Mathematics is ONLY the dual cycle of Free Generation (Syntax) vs. Quotienting (Semantics). This exhibit models the ontological cycle using Category Theory, proving that all mathematical structures arise from this duality. The Free Functor $F$ builds free paths (monoid strings) out of unstructured sets, generating syntactic lists without bounds. The Forgetful Functor $U$ collapses these paths back to raw elements, removing the monoid structure. The natural isomorphism of the adjunction $F \\dashv U$ bridges these two worlds, showing that syntactic paths and semantic elements are paired in an elegant mathematical correspondence.",
        rigor: "Mathematically, the dynamic process of free generation and quotienting is formally known as defining structures via 'Generators and Relations' (or 'Presentations'). This formalizes the 'Core Logic' connection: logical systems (Intuitionistic Logic) are presentations where propositional formulas are freely generated as syntax (generators) and quotiented by provable equivalence (relations) into a Heyting Algebra. For the adjunction $F \\dashv U$ between Sets $\\mathcal{C}$ and Monoids $\\mathcal{D}$, the Free Functor $F(S) = S^*$ builds the freely generated syntactic monoid. The adjunction establishes a natural isomorphism $\\text{Hom}_{\\mathcal{D}}(F(S), M) \\cong \\text{Hom}_{\\mathcal{C}}(S, U(M))$, showing that any semantic homomorphism is uniquely determined by quotienting the generator mappings.",
        history: "The history of algebra evolved from manipulating raw strings to the formalization of structures. Eilenberg and Mac Lane introduced category theory in 1945, recognizing that functors and adjunctions model intellectual operations. The Free Functor $F$ formalizes the free generation of expression syntax, while the Forgetful Functor $U$ formalizes quotienting to semantics. This adjunction represents the mathematical crystallization of the ontological cycle, proving that all mathematical structures are exclusively generated by the dual cycle of free generation and quotienting.",
        exercises: "1. Let the generator set be $S = \\{x, y\\}$. Generate the free monoid path syntax of length $\\le 2$ via the Free Functor $F$.\n2. Apply the Forgetful Functor $U$ to a monoid path $x-y-z$ and explain how this structural collapse back to raw elements reflects the quotienting of syntax to reveal semantic primitives. Prove how the Heyting algebra collapse in core logic mirrors this adjunction."
      },
      ja: {
        narrative: "数学は、自由生成（構文）と商化（意味論）の双対サイクル「のみ」で構成されています。この展示では、圏論を用いて存在論的サイクルをモデル化し、すべての数学的構造がこの双対性から生じることを証明します。自由関手 $F$ は、構造のない集合から自由な構文パス（モノイド文字列）を自由に生成し、無制限の構文リストを作成します。忘却関手 $U$ は、これらのパスを生の要素へと崩壊させます。随伴関係 $F \\dashv U$ の自然同型は、これらの世界を架け橋し、構文的なパスと意味的な要素がエレガントな対応関係でペアになっていることを示します。",
        rigor: "数学において、自由生成と商化の動的なプロセスは、公式には「生成元と関係式」（あるいは「プレゼンテーション」）による構造の定義として知られています。これは「核心的論理（Core Logic）」の接続を形式化します。論理体系（直観主義論理）は、命題論理式が構文（生成元）として自由生成され、証明可能な同値関係（関係式）によってハイティング代数（古典論理の場合はブール代数）へと商化されるプレゼンテーションです。集合の圏 $\\mathcal{C}$ とモノイドの圏 $\\mathcal{D}$ の間の随伴 $F \\dashv U$ において、自由関手 $F(S) = S^*$ は自由生成された構文モノイドを構築し、自然同型 $\\text{Hom}_{\\mathcal{D}}(F(S), M) \\cong \\text{Hom}_{\\mathcal{C}}(S, U(M))$ を通して、いかなる意味的準同型写像も生成元写像の商化によって一意に決定されることを示します。",
        history: "代数史は、生の文字列の操作から構造の形式化へと進化しました。エイレンバーグとマックレーンは1945年に圏論を導入し、関手と随伴関係が知的な操作をモデル化することを認識しました。自由関手 $F$ は式構文の自由生成を形式化し、忘却関手 $U$ は意味論への商化を形式化します。この随伴関係は、存在論的サイクルの数学的結晶化を表しており、すべての数学的構造が自由生成と商化の双対サイクル「のみ」によって生成されることを証明しています。",
        exercises: "1. 生成元集合を $S = \\{x, y\\}$ とします。自由関手 $F$ を用いて、長さ $\\le 2$ の自由モノイドパス構文を生成してください。\n2. モノイドパス $x-y-z$ に忘却関手 $U$ を適用し、この生の要素への構造的崩壊が、意味的な原始元を明らかにするための構文の商化をどのように反映しているか説明してください。核心的論理におけるハイティング代数の崩壊がこの随伴関係をどのように鏡映しているかを証明してください。"
      }
    }[language];
  }, [language]);

  // Text-to-Speech (TTS) states
  const [activeSpeechText, setActiveSpeechText] = useState<string | null>(null);
  const [voices, setVoices] = useState<SpeechSynthesisVoice[]>([]);
  const [selectedVoiceName, setSelectedVoiceName] = useState<string>('');
  const [currentCharIndex, setCurrentCharIndex] = useState<number>(-1);
  const [speedMultiplier, setSpeedMultiplier] = useState<number>(1.0);
  const [isPaused, setIsPaused] = useState<boolean>(false);
  const [activeTab, setActiveTab] = useState<'narrative' | 'rigor' | 'history' | 'exercises'>('narrative');

  // Load voices dynamically based on active language selection
  useEffect(() => {
    if (!('speechSynthesis' in window)) return;

    const loadVoices = () => {
      const allVoices = window.speechSynthesis.getVoices();
      
      const langPrefix = language === 'ja' ? 'ja' : 'en';
      const filteredVoices = allVoices.filter(v => v.lang.startsWith(langPrefix));
      setVoices(filteredVoices);

      // Auto-select US English Neural voices
      const scoredVoices = filteredVoices.map(v => {
        let score = 0;
        const nameLower = v.name.toLowerCase();
        const langLower = v.lang.toLowerCase();

        if (language === 'en') {
          if (langLower.includes('en-us') || langLower.includes('en_us')) score += 100;
          if (nameLower.includes('natural') || nameLower.includes('neural') || nameLower.includes('online')) score += 50;
          if (nameLower.includes('google') || nameLower.includes('microsoft') || nameLower.includes('apple')) score += 30;
          if (nameLower.includes('aria') || nameLower.includes('guy') || nameLower.includes('samantha') || nameLower.includes('female') || nameLower.includes('male')) score += 20;
        } else {
          if (nameLower.includes('google') || nameLower.includes('natural') || nameLower.includes('neural') || nameLower.includes('online')) score += 50;
          if (nameLower.includes('sayaka') || nameLower.includes('haruka')) score += 20;
        }
        return { voice: v, score };
      });

      scoredVoices.sort((a, b) => b.score - a.score);
      const bestVoice = scoredVoices[0]?.voice || filteredVoices[0];

      if (bestVoice) {
        setSelectedVoiceName(bestVoice.name);
      }
    };

    loadVoices();
    window.speechSynthesis.onvoiceschanged = loadVoices;
  }, [language]);

  // Reset elements labels depending on stop
  useEffect(() => {
    if (currentStop === 2) {
      setSetElements([
        { id: '1', label: 'I' },
        { id: '2', label: 'I' },
        { id: '3', label: 'I' }
      ]);
      setCounitInput('I-I-I');
    } else {
      setSetElements([
        { id: '1', label: 'x' },
        { id: '2', label: 'y' },
        { id: '3', label: 'z' }
      ]);
      setCounitInput('x-y-z');
    }
    setMonoidWords([]);
    setAnimationState('idle');
    setCounitResult(null);
  }, [currentStop]);

  // Stop speech when current stop, language, or active tab changes
  useEffect(() => {
    stopSpeechComplete();
  }, [currentStop, language, activeTab]);

  // Hot-reload speed multiplier mid-speech
  useEffect(() => {
    if (activeSpeechText) {
      const activeIdx = currentCharIndex >= 0 ? currentCharIndex : 0;
      startSpeech(activeSpeechText, activeIdx);
    }
  }, [speedMultiplier]);

  useEffect(() => {
    return () => {
      if ('speechSynthesis' in window) {
        window.speechSynthesis.cancel();
      }
    };
  }, []);

  const stopSpeechComplete = () => {
    if ('speechSynthesis' in window) {
      window.speechSynthesis.cancel();
    }
    if (activeUtteranceRef) {
      activeUtteranceRef = null;
    }
    setActiveSpeechText(null);
    setCurrentCharIndex(-1);
    setIsPaused(false);
  };

  const startSpeech = (text: string, startIndex: number) => {
    if (!('speechSynthesis' in window)) return;
    window.speechSynthesis.cancel();
    
    // Introduce a brief timeout to let the browser cancel process complete
    setTimeout(() => {
      const sliceText = text.substring(startIndex);
      if (!sliceText.trim()) {
        stopSpeechComplete();
        return;
      }

      const cleanText = ", " + sliceText.replace(/[\$\{\}\[\]\(\)⊣→≅↦]/g, ' '); 
      const utterance = new SpeechSynthesisUtterance(cleanText);
      activeUtteranceRef = utterance; // Prevent garbage collection
      
      const voice = voices.find(v => v.name === selectedVoiceName);
      if (voice) {
        utterance.voice = voice;
      }

      const baseRate = language === 'ja' ? 0.95 : 0.92;
      utterance.rate = baseRate * speedMultiplier;
      utterance.pitch = 1.0;

      utterance.onboundary = (event) => {
        if (event.name === 'word') {
          const adjustedCharIdx = event.charIndex - 2;
          if (adjustedCharIdx >= 0) {
            const currentIdx = startIndex + adjustedCharIdx;
            setCurrentCharIndex(currentIdx);
            
            // Extract the word that is currently being spoken
            const spokenWord = getWordAtCharIndex(text, currentIdx);
            if (spokenWord) {
              handleSpeechTrigger(spokenWord);
            }
          }
        }
      };

      utterance.onend = () => {
        setTimeout(() => {
          if (!window.speechSynthesis.speaking && !window.speechSynthesis.pending) {
            stopSpeechComplete();
          }
        }, 60);
      };

      utterance.onerror = () => {
        stopSpeechComplete();
      };

      window.speechSynthesis.speak(utterance);
      setActiveSpeechText(text);
      setIsPaused(false);
      setCurrentCharIndex(startIndex);
    }, 100);
  };

  const speakCurrentStop = (text: string) => {
    if (!('speechSynthesis' in window)) return;

    if (activeSpeechText === text) {
      if (isPaused) {
        window.speechSynthesis.resume();
        setIsPaused(false);
      } else {
        window.speechSynthesis.pause();
        setIsPaused(true);
      }
    } else {
      startSpeech(text, 0);
    }
  };

  const handleSeek = (direction: 'fwd' | 'rwd') => {
    if (!activeSpeechText) return;
    const words = getSpokenWords(activeSpeechText, language);
    if (words.length === 0) return;

    // Locate active word index
    let currentWordIdx = words.findIndex(
      w => currentCharIndex >= w.start && currentCharIndex <= w.end
    );
    if (currentWordIdx === -1) {
      currentWordIdx = words.findIndex(w => w.start > currentCharIndex);
      if (currentWordIdx === -1) currentWordIdx = words.length - 1;
    }

    const wordSkip = 4;
    let targetWordIdx = direction === 'fwd' 
      ? Math.min(words.length - 1, currentWordIdx + wordSkip) 
      : Math.max(0, currentWordIdx - wordSkip);

    const targetWord = words[targetWordIdx];
    startSpeech(activeSpeechText, targetWord.start);
  };

  const addElement = () => {
    const labels = currentStop === 2 
      ? ['I', 'I', 'I', 'I', 'I', 'I']
      : ['x', 'y', 'z', 'w', 'u', 'v', 'a', 'b', 'c'];
    
    if (currentStop === 2) {
      if (setElements.length >= 8) return;
      const newId = (setElements.length + 1).toString();
      setSetElements([...setElements, { id: newId, label: 'I' }]);
    } else {
      const usedLabels = setElements.map(e => e.label);
      const available = labels.filter(l => !usedLabels.includes(l));
      if (available.length === 0) return;
      const nextLabel = available[0];
      const newId = (setElements.length + 1).toString();
      setSetElements([...setElements, { id: newId, label: nextLabel }]);
    }
    setMonoidWords([]);
  };

  const clearElements = () => {
    setSetElements([]);
    setMonoidWords([]);
    setAnimationState('idle');
    setCounitResult(null);
    stopSpeechComplete();
  };

  // Functor F: Free Generation
  const triggerFreeGeneration = () => {
    setAnimationState('free');
    setCounitResult(null);
    setTimeout(() => {
      const letters = setElements.map(e => e.label);
      if (letters.length === 0) {
        setMonoidWords(currentStop === 2 ? ['0 (empty)'] : ['ε (empty)']);
        return;
      }
      
      const generated: string[] = currentStop === 2 ? ['0'] : ['ε']; 
      if (currentStop === 2) {
        let tally = '';
        letters.forEach(() => {
          tally += 'I';
          generated.push(tally);
        });
      } else {
        letters.forEach(l => generated.push(`[${l}]`));
        if (letters.length >= 2) {
          for (let i = 0; i < letters.length - 1; i++) {
            generated.push(`[${letters[i]},${letters[i+1]}]`);
          }
        }
        if (letters.length >= 3) {
          generated.push(`[${letters.slice(0, 3).join(',')}]`);
        }
      }
      
      setMonoidWords(generated);
    }, 800);
  };

  // Functor U: Forgetful
  const triggerForgetfulCollapse = () => {
    setAnimationState('forget');
    setTimeout(() => {
      setMonoidWords([]);
    }, 800);
  };

  // Unit of Adjunction
  const triggerUnitMap = () => {
    setAnimationState('unit');
    triggerFreeGeneration();
  };

  // Counit of Adjunction
  const triggerCounitCollapse = () => {
    setAnimationState('counit');
    const parts = counitInput.split('-');
    if (currentStop === 2) {
      const sum = parts.join('').length;
      setTimeout(() => {
        setCounitResult(sum.toString() + ' (mammoths / objects)');
      }, 1000);
    } else {
      const product = parts.join('');
      setTimeout(() => {
        setCounitResult(product);
      }, 1000);
    }
  };

  const getWordAtCharIndex = (text: string, charIdx: number): string | null => {
    const words = getSpokenWords(text, language);
    const match = words.find(w => charIdx >= w.start && charIdx < w.end);
    return match ? match.text : null;
  };

  const handleSpeechTrigger = (word: string) => {
    const w = word.toLowerCase();
    if (w.includes('free') || w.includes('functor') || w.includes('generate') || w.includes('path') || w.includes('monoid') || 
        w.includes('自由') || w.includes('関手') || w.includes('生成') || w.includes('経路') || w.includes('モノイド')) {
      triggerFreeGeneration();
    } else if (w.includes('forgetful') || w.includes('collapse') || w.includes('forget') || w.includes('isomorphism') || 
               w.includes('忘却') || w.includes('崩壊') || w.includes('忘れる') || w.includes('同型')) {
      triggerForgetfulCollapse();
    } else if (w.includes('unit') || w.includes('counit') || w.includes('adjoining') || w.includes('adjunction') || 
               w.includes('随伴') || w.includes('単位') || w.includes('余単位')) {
      if (w.includes('counit') || w.includes('余単位')) {
        triggerCounitCollapse();
      } else {
        triggerUnitMap();
      }
    }
  };

  // Tokenize text into segments with positions
  const getSpokenWords = (text: string, lang: 'en' | 'ja'): SpokenWord[] => {
    const words: SpokenWord[] = [];
    if (lang === 'ja') {
      for (let i = 0; i < text.length; i++) {
        words.push({ text: text[i], start: i, end: i + 1 });
      }
    } else {
      const wordRegex = /[a-zA-Z0-9'’⊣→≅↦ηε\(\)\{\}\-\:\,]+/g;
      let match;
      while ((match = wordRegex.exec(text)) !== null) {
        words.push({
          text: match[0],
          start: match.index,
          end: match.index + match[0].length
        });
      }
    }
    return words;
  };

  // Renders spoken words in Spans for real-time gold highlighting
  const renderHighlightedText = (text: string) => {
    const words = getSpokenWords(text, language);
    let result: React.ReactNode[] = [];
    let lastIdx = 0;
    
    words.forEach((w, idx) => {
      if (w.start > lastIdx) {
        result.push(text.substring(lastIdx, w.start));
      }
      
      const isCurrent = currentCharIndex >= w.start && currentCharIndex < w.end;
      result.push(
        <span 
          key={idx} 
          className={isCurrent ? "word-highlight" : "word-normal"}
          onClick={() => startSpeech(text, w.start)}
          title={language === 'en' ? 'Click to play from here' : 'ここから再生'}
        >
          {w.text}
        </span>
      );
      lastIdx = w.end;
    });
    
    if (lastIdx < text.length) {
      result.push(text.substring(lastIdx));
    }
    
    return result;
  };

  const nextStop = () => {
    if (currentStop < tourStops.length) {
      setCurrentStop(currentStop + 1);
    }
  };

  // Tour stops definitions (Gradual, rigorous buildup of Free Generation & Quotients)
  const tourStops: TourStop[] = language === 'ja' ? [
    {
      id: 1,
      title: "I. 美術館入口：存在論的サイクル",
      subtitle: "人類が記法と意味論を通じて存在を発見した物語。",
      text: "随伴存在論ツアーへようこそ。数学はその究極の基盤において、自由生成と商化という２つの認知の対話的サイクルそのものです。私たちは最初に文字や記号を一切の制約なしに並べて「構文（Syntax）」を作り出し、次にそれらを方程式によって特定の価値へと折りたたむことで「意味論（Semantics）」を与えます。この一見単純なプロセスこそがすべての数学的構造の起源です。本ツアーでは、骨の刻み目から言語の文法、そして圏論へとこの二重性を段階的に追っていきます。"
    },
    {
      id: 2,
      title: "II. 数え上げの黎明：石ころと刻み目 (百万年前)",
      subtitle: "無制限に刻み目を打つ「自由生成」と、個数へ折りたたむ「商化」。",
      text: "百万年前、私たちの祖先は骨に刻み目（ノッチ）を刻み始めました。追加のルールを持たずに、刻み目 I を I, II, III と無数に刻み続ける行為は、純粋な記号構文の「自由生成」です。しかし、バラバラの刻み目そのものは役に立ちません。これを「5頭の獲物」という単一の数概念へと折りたたむ行為、これこそが「商化」です。バラバラな表記を同値関係でまとめ上げることで、私たちは数を把握したのです。"
    },
    {
      id: 3,
      title: "III. 言語の誕生：アルファベットと意味論 (古代)",
      subtitle: "アルファベットから無限の文を生成し、共通概念へと商化させる。",
      text: "文字を手に入れた人類は、少数の記号から無限の言葉や文を紡ぎ出す能力を獲得しました。ルールを無視してアルファベットを自由に並べる行為は、無制限な記号空間の「自由生成」です。しかし、綴りや言い回しが異なっていても、伝わる核心的なイメージは一つに収縮します。私たちは異なる表現を「同義」としてグループ化（商化）することで、言語に共通の意味論を与えたのです。"
    },
    {
      id: 4,
      title: "IV. アルゴリズムの時代：構文木とコンパイル (現代)",
      subtitle: "コード構文を生成し、コンピューターで評価して値へ崩壊させる。",
      text: "現代のコンピューターサイエンスも、このサイクルを共有しています。コードを書く際、私たちは変数や演算子を自由に並べて「抽象構文木（AST）」を生成します。そしてコンパイラやCPUが二項演算に従って式を再帰的に評価し、最終的な出力値へと「崩壊（Quotient Collapse）」させます。コードの記述が自由生成であり、その実行が商化による値の導出に他なりません。"
    },
    {
      id: 5,
      title: "V. 定式化：集合とモノイドの圏",
      subtitle: "認知の往復を、数学的なオブジェクトの接続として記述する。",
      text: "この知性の往復を、圏論を用いて正式に定義します。構造を持たない生の記号の世界を「集合の圏C」とし、結合ルールを持つ体系を「モノイドの圏D」と呼びます。集合から自由な文字列を作る操作は「自由関手F」であり、モノイドから演算構造を無視して生の文字列に戻す操作は「忘却関手U」です。これらは２つの世界の架け橋です。"
    },
    {
      id: 6,
      title: "VI. 定式化：随伴 duality (F ⊣ U)",
      subtitle: "自由生成と商化崩壊を完璧に統合する自然同型。",
      text: "自由生成と商化のループは、圏論において「随伴（F ⊣ U）」として統合されます。これは、自由モノイド上のすべての準同型写像（崩壊のルール）が、元の生の要素をどこに送るかという最初の写像だけで一意に決定されることを意味します。百万年前に小石を数え始めた人類の思考の必然が、数学の最も美しい随伴の橋によって証明されるのです。"
    }
  ] : [
    {
      id: 1,
      title: "I. Gallery Entrance: The Ontological Cycle",
      subtitle: "The absolute nature of mathematical existence.",
      text: "Welcome to the Ontology Museum Tour. At its ultimate foundation, mathematics is the dialogical cycle of Free Generation and Quotienting. Every mathematical system is constructed by first freely generating a syntax or space of elements, and then collapsing it by imposing relations and equations to resolve semantics. In this tour, we will explore this duality step-by-step, starting from bone notches and language grammar, to formal Category Theory."
    },
    {
      id: 2,
      title: "II. The Dawn of Counting: Pebbles and Notches (1M Years Ago)",
      subtitle: "Generating notches freely and collapsing them into numeric quantities.",
      text: "A million years ago, our ancestors carved notches on bones to record quantity. Carving notches I, II, III freely with no rules is the free generation of pure syntax. However, raw notches are useless on their own. Folding those discrete marks into a single numeric concept, such as 5, to trade, compare, or share is the quotient collapse. By grouping syntactic marks under bijection, we discovered numbers."
    },
    {
      id: 3,
      title: "III. The Birth of Language: Alphabet & Semantics (Ancient Eras)",
      subtitle: "Generating infinite strings of text and collapsing them into shared meaning.",
      text: "With alphabets, humanity gained the ability to generate infinite sentences. Arranging letters freely to write down expressions represents the free generation of syntax. Quotienting is the mechanism of semantics, where multiple different syntactic formulations or synonyms collapse under a single equivalence class representing a shared definition or meaning."
    },
    {
      id: 4,
      title: "IV. The Algorithmic Era: Syntax Trees & Evaluation (Modern)",
      subtitle: "Generating abstract syntax trees and collapsing them into values.",
      text: "Modern computer science follows the exact same cognitive cycle. We freely assemble variables and operators into nested Abstract Syntax Trees (Syntax). The CPU or compiler then collapses this tree using binary operations, reducing it into a single computed output value (Evaluation). Writing code is free generation, while executing it is quotient collapse."
    },
    {
      id: 5,
      title: "V. Formalization: Categories of Sets & Monoids",
      subtitle: "Representing our cognitive cycle with objects and structured categories.",
      text: "We now introduce Category Theory to formalize this cognitive loop mathematically. Category C of Sets represents the world of raw elements (notches, variables) without structure. Category D of Monoids represents structured objects with associative multiplication. Free generation is represented as the Free Functor F, and collapse is represented as the Forgetful Functor U."
    },
    {
      id: 6,
      title: "VI. Formalization: The Adjunction Duality (F ⊣ U)",
      subtitle: "The natural isomorphism uniting notation and meaning.",
      text: "The ultimate mathematical formalization of our ontology is the Adjunction. It establishes a natural isomorphism between hom-sets. This states that specifying a collapsed evaluation map out of a free structure is identical to choosing where the raw generators map. The cognitive circle that began with notch-carving a million years ago is mathematically unified."
    }
  ];

  const isSpeaking = activeSpeechText === tabContent[activeTab];

  return (
    <div className="visualizer-container animate-pop-in">
      
      {/* Prominent Segmented Room Navigation Dashboard */}
      <nav className="room-nav-tabs">
        {[1, 2, 3, 4, 5, 6].map((num) => {
          const roman = ['I', 'II', 'III', 'IV', 'V', 'VI'][num - 1];
          const isActive = currentStop === num;
          return (
            <button
              key={num}
              onClick={() => setCurrentStop(num)}
              className={`room-tab-btn ${isActive ? 'active' : ''}`}
            >
              <span className="room-tab-num">{roman}</span>
              <span className="room-tab-title">
                {language === 'en' 
                  ? ['Entrance', 'Counting', 'Language', 'Algorithms', 'Categories', 'Adjunction'][num - 1]
                  : ['入口', '数え上げ', '言語', '計算機', '定式化', '随伴'][num - 1]
                }
              </span>
            </button>
          );
        })}
      </nav>

      {/* Museum Guide Nav Controller (Audio Guide Device Mock-up) */}
      <div className="audio-guide-player">
        
        {/* Device Brand & Screen */}
        <div className="device-info">
          <div className="device-screen" style={{ fontFamily: 'monospace', fontSize: '0.65rem' }}>
            {isSpeaking ? 'ON' : 'OFF'}
          </div>
          <div className="device-meta">
            <h4>{language === 'en' ? 'Audio Companion Guide' : '解説ガイドレシーバー'}</h4>
            <p>{language === 'en' ? 'Exhibition Sound Guide' : '展示音声アナウンス'}</p>
          </div>
        </div>

        {/* Dynamic Voice Selection */}
        <div className="audio-controls-group" style={{ gap: '0.75rem' }}>
          {voices.length > 0 && (
            <select
              value={selectedVoiceName}
              onChange={(e) => setSelectedVoiceName(e.target.value)}
              className="input-text"
              style={{ 
                width: '100px', 
                fontSize: '0.6rem', 
                padding: '1px 4px', 
                height: '24px', 
                background: 'rgba(0,0,0,0.5)',
                border: '1px solid rgba(212,175,55,0.3)',
                color: 'var(--primary)',
                cursor: 'pointer',
                borderRadius: '6px'
              }}
            >
              {voices.map((v, i) => (
                <option key={i} value={v.name} style={{ background: '#0b0f19', color: '#fff' }}>
                  {v.name.replace('Microsoft', 'MS').replace('Google', 'G').replace('日本語', 'JP')}
                </option>
              ))}
            </select>
          )}

          {/* Speed Selector Menu */}
          <select
            value={speedMultiplier.toString()}
            onChange={(e) => setSpeedMultiplier(parseFloat(e.target.value))}
            className="input-text"
            style={{ 
              width: '64px', 
              fontSize: '0.65rem', 
              padding: '2px 4px', 
              height: '24px', 
              background: 'rgba(0,0,0,0.5)',
              border: '1px solid rgba(212,175,55,0.3)',
              color: 'var(--primary)',
              cursor: 'pointer',
              borderRadius: '6px'
            }}
            title={language === 'en' ? 'Playback Speed' : '再生速度'}
          >
            <option value="1" style={{ background: '#0b0f19', color: '#fff' }}>1.00x</option>
            <option value="1.25" style={{ background: '#0b0f19', color: '#fff' }}>1.25x</option>
            <option value="1.5" style={{ background: '#0b0f19', color: '#fff' }}>1.50x</option>
            <option value="2" style={{ background: '#0b0f19', color: '#fff' }}>2.00x</option>
          </select>

          {/* Player controls */}
          <div style={{ display: 'flex', alignItems: 'center', gap: '0.35rem' }}>
            
            {/* Rewind Word-by-Word */}
            <button
              onClick={() => handleSeek('rwd')}
              disabled={!isSpeaking}
              className="btn btn-outline"
              style={{ width: '24px', height: '24px', padding: '0', display: 'flex', alignItems: 'center', justifyContent: 'center' }}
              title={language === 'en' ? 'Rewind' : '巻き戻し'}
            >
              <Rewind size={10} />
            </button>

            {/* Play / Pause Toggle */}
            <button
              onClick={() => speakCurrentStop(tabContent[activeTab])}
              className="btn btn-primary"
              style={{ width: '28px', height: '28px', padding: '0', display: 'flex', alignItems: 'center', justifyContent: 'center', borderRadius: '50%' }}
              title={isSpeaking && !isPaused ? (language === 'en' ? 'Pause' : '一時停止') : (language === 'en' ? 'Play' : '再生')}
            >
              {isSpeaking && !isPaused ? <Pause size={10} /> : <Play size={10} />}
            </button>

            {/* Fast-Forward Word-by-Word */}
            <button
              onClick={() => handleSeek('fwd')}
              disabled={!isSpeaking}
              className="btn btn-outline"
              style={{ width: '24px', height: '24px', padding: '0', display: 'flex', alignItems: 'center', justifyContent: 'center' }}
              title={language === 'en' ? 'Fast-Forward' : '早送り'}
            >
              <FastForward size={10} />
            </button>

            {/* Stop Speech */}
            <button
              onClick={stopSpeechComplete}
              disabled={!activeSpeechText}
              className="btn btn-outline"
              style={{ width: '24px', height: '24px', padding: '0', display: 'flex', alignItems: 'center', justifyContent: 'center', borderColor: activeSpeechText ? 'var(--error)' : 'rgba(255,255,255,0.1)' }}
              title={language === 'en' ? 'Stop' : '停止'}
            >
              <Square size={10} style={{ fill: activeSpeechText ? 'var(--error)' : 'none', color: activeSpeechText ? 'var(--error)' : 'currentColor' }} />
            </button>
          </div>
        </div>

      </div>

      {/* Main Museum Exhibit Display */}
      <div className="exhibit-grid">
        
        {/* Left Column: Audio Guide Transcript & Explanations (The Placard Card) */}
        <div className="placard-panel">
          <div>
            <div className="placard-header">
              <BookOpen size={12} />
              <span>{language === 'en' ? 'Gallery Placard' : '展示説明'}</span>
            </div>
            
            <div className="animate-pop-in">
              <h3 className="placard-title">
                {language === 'en' ? 'The Adjunction Bridge' : '随伴の架け橋'}
              </h3>
              <p className="placard-subtitle">
                {language === 'en' ? 'Unifying notation and meaning via F ⊣ U' : '自由関手と忘却関手による構文と意味の統合'}
              </p>

              {/* Tab Selector */}
              <div className="placard-tabs" style={{ display: 'flex', gap: '0.35rem', marginBottom: '1.25rem', borderBottom: '1px solid rgba(255,255,255,0.08)', paddingBottom: '0.5rem' }}>
                {(['narrative', 'rigor', 'history', 'exercises'] as const).map(tab => (
                  <button
                    key={tab}
                    onClick={() => setActiveTab(tab)}
                    className={`btn-lang ${activeTab === tab ? 'active' : ''}`}
                    style={{ fontSize: '0.68rem', padding: '4px 8px', textTransform: 'uppercase', letterSpacing: '0.05em' }}
                  >
                    {tab === 'narrative' ? (language === 'en' ? 'Narrative' : '叙事') :
                     tab === 'rigor' ? (language === 'en' ? 'Mathematical Rigor' : '数学的厳密性') :
                     tab === 'history' ? (language === 'en' ? 'Historical Context' : '歴史的背景') :
                     (language === 'en' ? 'Exercises' : '演習')}
                  </button>
                ))}
              </div>

              <div className="placard-text" style={{ fontSize: '0.85rem', lineHeight: '1.6', color: 'var(--text-muted)', minHeight: '140px', whiteSpace: 'pre-line' }}>
                <p>
                  {renderHighlightedText(tabContent[activeTab])}
                </p>
              </div>
            </div>
          </div>

          <div className="placard-footer">
            <span>TNG COOP EXHIBITION</span>
            <span>STATION {currentStop}/6</span>
          </div>
        </div>

        {/* Right Column: Dynamic Interactive Exhibit Area (The Kiosk Screen) */}
        <div className="kiosk-panel">
          
          {/* STOP 1: Entrance */}
          {currentStop === 1 && (
            <div className="entrance-display animate-pop-in">
              <div className="entrance-icon-container">
                <Layers size={32} />
              </div>
              <h4>{language === 'en' ? 'Free Generation & Collapse' : '自由生成と崩壊'}</h4>
              <p>
                {language === 'en'
                  ? 'Step inside the interactive exhibits. Click below to enter the Sets gallery room, representing raw mathematical generators.'
                  : '対話型の展示室に入ります。以下をクリックして、生の数学的生成元を表す「集合（Sets）展示室」に進んでください。'
                }
              </p>
              <button onClick={nextStop} className="btn btn-primary">
                {language === 'en' ? 'Enter Sets Gallery' : '集合展示室へ進む'} <ChevronRight size={12} />
              </button>
            </div>
          )}

          {/* STOP 2: The Dawn of Counting (Pebbles & Notches) */}
          {currentStop === 2 && (
            <div className="animate-pop-in" style={{ display: 'flex', flexDirection: 'column', justifyContent: 'space-between', height: '100%', width: '100%' }}>
              <div>
                <div className="workspace-title-bar">
                  <h4 className="workspace-title">{language === 'en' ? 'Notch Tally Workspace' : 'ノッチ集計ワークスペース'}</h4>
                  <div className="workspace-controls">
                    <button onClick={addElement} className="btn btn-primary">
                      {language === 'en' ? '+ Carve Notch' : '+ 刻み目を刻む'}
                    </button>
                    <button onClick={clearElements} className="btn btn-secondary" style={{ borderColor: 'rgba(239, 68, 68, 0.3)', color: 'var(--error)' }}>
                      {language === 'en' ? 'Clear Notches' : 'ノッチを消去'}
                    </button>
                  </div>
                </div>
                
                <div className="workspace-canvas">
                  {setElements.length === 0 ? (
                    <span className="empty-state">
                      {language === 'en' ? 'No notches carved yet.' : '刻み目がまだありません。'}
                    </span>
                  ) : (
                    setElements.map((e, index) => (
                      <div
                        key={index}
                        className="set-element floating-node"
                        style={{ borderStyle: 'dashed', borderRadius: '4px', width: '2rem', height: '3.5rem', fontFamily: 'monospace' }}
                      >
                        {e.label}
                      </div>
                    ))
                  )}
                </div>
              </div>
              
              <div className="workspace-footer">
                <span>{language === 'en' ? 'Carve notches freely, then proceed to Room III to collapse them.' : 'ノッチを自由に刻んだら、第3室に進んで数へ折りたたんでください。'}</span>
                <button onClick={nextStop} className="btn btn-primary">
                  {language === 'en' ? 'Go to Collapse' : '崩壊・商化室へ'} <ChevronRight size={10} />
                </button>
              </div>
            </div>
          )}

          {/* STOP 3: Pure Quotient Collapse (Folding words) */}
          {currentStop === 3 && (
            <div className="animate-pop-in" style={{ display: 'flex', flexDirection: 'column', justifyContent: 'space-between', height: '100%', width: '100%' }}>
              <div>
                <h4 className="workspace-title" style={{ marginBottom: '1.5rem' }}>
                  {language === 'en' ? 'Quotient Collapse' : '商化・崩壊'}
                </h4>
                <p className="placard-text" style={{ fontSize: '0.8rem', marginBottom: '1rem' }}>
                  {language === 'en'
                    ? 'Enter hyphenated tally marks (e.g. I-I-I) or words, and collapse them into a single numeric concept or meaning:'
                    : 'ハイフンで区切られたノッチ（例: I-I-I）や単語を入力し、二項演算（積）によって一つの概念へ崩壊させてください：'
                  }
                </p>
                <form onSubmit={handleCounitCollapse} className="counit-form">
                  <input
                    type="text"
                    value={counitInput}
                    onChange={e => setCounitInput(e.target.value)}
                    placeholder="I-I-I"
                    className="input-text"
                    required
                  />
                  <button type="submit" className="btn btn-primary">
                    {language === 'en' ? 'Collapse' : '崩壊させる'}
                  </button>
                </form>

                <div className="workspace-canvas" style={{ minHeight: '120px' }}>
                  {animationState === 'counit' && (
                    <div className="counit-result-box" style={{ width: '100%', border: 'none', background: 'transparent', minHeight: 'auto' }}>
                      {counitResult ? (
                        <span className="counit-val-result flex items-center gap-1.5" style={{ color: 'var(--success)', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                          <CheckCircle2 size={16} /> {language === 'en' ? 'Product:' : '評価結果:'} <span className="font-mono text-secondary ml-2 text-base">{counitResult}</span>
                        </span>
                      ) : (
                        <span className="counit-loading-text">
                          {language === 'en' ? 'FOLDING SYNTAX...' : '構文の折りたたみ・商化中...'}
                        </span>
                      )}
                    </div>
                  )}
                </div>
              </div>
            </div>
          )}

          {/* STOP 4: The Dual Play */}
          {currentStop === 4 && (
            <div className="animate-pop-in" style={{ display: 'flex', flexDirection: 'column', justifyContent: 'space-between', height: '100%', width: '100%' }}>
              <div>
                <h4 className="workspace-title" style={{ marginBottom: '1rem' }}>
                  {language === 'en' ? 'Dual Play: Inclusion & Evaluation' : '双対の戯れ：包摂と評価'}
                </h4>
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem', marginBottom: '1rem' }}>
                  <button onClick={triggerUnitMap} disabled={setElements.length === 0} className="btn btn-primary text-[9px]">
                    {language === 'en' ? '1. Trigger η_X' : '1. 包摂 (η_X) を実行'}
                  </button>
                  <button onClick={triggerCounitCollapse} className="btn btn-secondary text-[9px]">
                    {language === 'en' ? '2. Trigger ε_M' : '2. 評価 (ε_M) を実行'}
                  </button>
                </div>

                <div className="unit-list" style={{ maxHeight: '140px' }}>
                  {setElements.map((e, index) => (
                    <div key={index} className="unit-row">
                      <span className="unit-val-src">{e.label}</span>
                      <ArrowRight size={12} className="text-text-muted" />
                      <span className="unit-val-target">
                        {animationState === 'unit' ? `[${e.label}]` : '?'}
                      </span>
                      <span className="unit-val-desc" style={{ fontSize: '9px' }}>
                        {animationState === 'unit' 
                          ? (language === 'en' ? 'singleton (η)' : '単一単語 (η)') 
                          : (language === 'en' ? 'raw element' : '生の要素')
                        }
                      </span>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          )}

          {/* STOP 5: Categories of Sets and Monoids */}
          {currentStop === 5 && (
            <div className="animate-pop-in" style={{ display: 'flex', flexDirection: 'column', justifyContent: 'space-between', height: '100%', width: '100%' }}>
              <div>
                <h4 className="workspace-title" style={{ marginBottom: '1rem' }}>
                  {language === 'en' ? 'Mapping between Categories C and D' : '圏 C と 圏 D の間の写像'}
                </h4>
                
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '0.75rem', marginBottom: '1.5rem' }}>
                  <button onClick={triggerFreeGeneration} disabled={setElements.length === 0} className="btn btn-primary">
                    {language === 'en' ? 'Apply Functor F' : '関手 F を適用'}
                  </button>
                  <button onClick={triggerForgetfulCollapse} disabled={monoidWords.length === 0} className="btn btn-secondary">
                    {language === 'en' ? 'Apply Functor U' : '関手 U を適用'}
                  </button>
                </div>

                <div className="workspace-canvas">
                  {monoidWords.length === 0 ? (
                    <span className="empty-state">
                      {language === 'en' ? 'No structure. Categories disconnected.' : '構造なし。圏の接続は切断されています。'}
                    </span>
                  ) : (
                    <div className="monoid-words-grid">
                      {monoidWords.map((word, idx) => (
                        <div key={idx} className="monoid-item floating-node">
                          {word}
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              </div>
            </div>
          )}

          {/* STOP 6: Adjunction Duality (F ⊣ U) */}
          {currentStop === 6 && (
            <div className="animate-pop-in text-center">
              <div className="bridge-box">
                <div className="bridge-term primary">hom(F(X), M)</div>
                <div className="bridge-iso-symbol">≅</div>
                <div className="bridge-term secondary">hom(X, U(M))</div>
              </div>
              <h4 className="bridge-label">{language === 'en' ? 'Natural Isomorphism Duality' : '自然同型の双対性'}</h4>
              <p className="bridge-text">
                {language === 'en'
                  ? 'Universal property of free monoids. Mapping plain elements to any monoid automatically, uniquely induces a full structure-preserving Monoid Homomorphism out of the Free Monoid.'
                  : '自由モノイドの普遍的性質。構造を持たない集合の要素から他のモノイドへの写像を定義すると、それは自動的かつ一意に自由モノイドからの構造保存準同型写像を誘起します。'
                }
              </p>
            </div>
          )}

        </div>

      </div>

    </div>
  );

  function handleCounitCollapse(e: React.FormEvent) {
    e.preventDefault();
    setCounitResult(null);
    triggerCounitCollapse();
  }
}
