import React, { useState, useEffect, useMemo, useRef } from 'react';
import { Play, Pause, Layers, RefreshCw, Square, FastForward, Rewind, BookOpen } from 'lucide-react';

interface Point2D {
  x: number; // normalized [0, 1]
  y: number; // normalized [0, 1]
}

interface Hall3VisualizerProps {
  language: 'en' | 'ja';
  onlyVisualizer?: boolean;
}

type ProjectedItem =
  | {
      type: 'grid-line';
      id: string;
      pathData: string;
      color: string;
      strokeWidth: number;
      opacity: number;
      depth: number;
    }
  | {
      type: 'point';
      id: string;
      cx: number;
      cy: number;
      color: string;
      depth: number;
    };

interface SpokenWord {
  text: string;
  start: number;
  end: number;
}

let activeUtteranceRef: SpeechSynthesisUtterance | null = null;

export default function Hall3Visualizer({ language, onlyVisualizer = false }: Hall3VisualizerProps) {
  // Translations
  const t = useMemo(() => {
    const translations = {
      en: {
        roomTitle: "Exhibits / Hall 3: Quotient Topology",
        title: "The Quotient Torus",
        subtitle: "Folding a 2D sheet into a 3D manifold via boundary gluing",
        description1: "In topology, a quotient space is formed by gluing together points of a given space under an equivalence relation. Here, we start with a flat, two-dimensional square sheet and glue its opposite boundaries.",
        description2: "First, we glue the top boundary (Gold A) to the bottom boundary (Gold A) in the same direction. This forms a cylinder. Next, we glue the left boundary (Cyan B) to the right boundary (Cyan B), bending the cylinder to glue its circular ends. This yields a torus.",
        description3: "Move your cursor or tap over the 2D sheet to place a point. Observe its equivalence class: points on the boundaries or corners correspond to the exact same point in the glued quotient space. Watch them merge in 3D as the gluing stage increases.",
        gluingStage: "Gluing Stage",
        stage0: "0: Flat Sheet",
        stage1: "1: Cylinder",
        stage2: "2: Torus",
        playFolding: "Play Folding",
        pauseFolding: "Pause Folding",
        spin: "Auto-Rotation",
        reset: "Reset Point",
        equivalenceClass: "Equivalence Class",
        instruction: "Hover or tap on the 2D sheet to place a point",
        dragPrompt: "Drag 3D model to rotate manually",
        boundaryA: "Boundary A (Top & Bottom → Cylinder)",
        boundaryB: "Boundary B (Left & Right → Torus)",
      },
      ja: {
        roomTitle: "展示 / 第3室：商位相空間",
        title: "商空間としてのトーラス",
        subtitle: "境界の接着による2次元平面から3次元多様体への折り畳み",
        description1: "トポロジー（位相幾何学）において、商位相空間とは、与えられた空間の点を同値関係に基づいて「接着」することによって形成される空間です。ここでは、平らな2次元の正方形シートから始め、その対向する境界を接着します。",
        description2: "まず、上部境界（金色 A）と下部境界（金色 A）を同じ向きに接着します。これにより円柱が形成されます。次に、左側境界（シアン B）と右側境界（シアン B）を接着し、円柱を曲げてその両端の円を接着します。これによりトーラス（ドーナツ型）が得られます。",
        description3: "2Dシート上をホバーまたはタップすると、点とその同値類が表示されます。境界上やコーナーにある点は、接着された商空間においてまったく同一の点に対応します。接着ステージを進めると、それらが3D空間で1つに融合していく様子を観察できます。",
        gluingStage: "接着ステージ",
        stage0: "0: 平らなシート",
        stage1: "1: 円柱",
        stage2: "2: トーラス",
        playFolding: "折り畳みを再生",
        pauseFolding: "一時停止",
        spin: "自動回転",
        reset: "点をリセット",
        equivalenceClass: "同値類",
        instruction: "2Dシート上をホバーまたはタップして点を配置してください",
        dragPrompt: "3Dモデルをドラッグして回転できます",
        boundaryA: "境界 A (上下接着 → 円柱)",
        boundaryB: "境界 B (左右接着 → トーラス)",
      }
    };
    return translations[language];
  }, [language]);

  const tabContent = useMemo(() => {
    return {
      en: {
        narrative: "Mathematics is ONLY the dual cycle of Free Generation (Syntax) vs. Quotienting (Semantics). In topology, this is visualized by taking flat, unconstrained 2D coordinates (free syntax generation) and folding them into a compact manifold. By quotienting opposite boundaries under the equivalence relation $x \\sim x+1$ and $y \\sim y+1$, the infinite boundaries collapse. What was a flat syntactic sheet is quotiented into a semantic 3D torus manifold, showing that topological shape is the semantic result of quotienting freely generated space.",
        rigor: "Mathematically, the process of free generation and quotienting is formally known as defining structures via 'Generators and Relations' (or 'Presentations'). The free generation phase constructs the topological space $X = [0, 1] \\times [0, 1] \\subset \\mathbb{R}^2$ with the standard subspace topology, representing unconstrained coordinates syntax. The quotient phase defines the equivalence relation $\\sim$ on $X$ generated by $(x, 0) \\sim (x, 1)$ and $(0, y) \\sim (1, y)$ for all $x, y \\in [0, 1]$. The quotient topology on $X/\\sim$ projects the open sets of the square into the glued space. This presentation constructs a quotient space homeomorphic to the torus $S^1 \\times S^1$, proving that topological manifolds are semantic quotient spaces of freely generated syntactic coordinates.",
        history: "The history of geometry shows that shape is not an inherent metric but a semantic quotient of a freely generated syntactic space. Henri Poincaré shifted mathematics from rigid coordinate syntax to global semantics by showing manifolds can be defined by boundary relations. This historical transition confirms the core philosophy that mathematical space is exclusively born from the dual cycle of free coordinate generation (syntax) followed by boundary quotienting (semantics).",
        exercises: "1. Locate the coordinate $(0, 0.5)$ in the freely generated 2D sheet. Find its glued partner under the quotient relation $x \\sim x+1$ that collapses it into the semantic torus.\n2. Prove that the four corners of the flat sheet $\{(0,0), (0,1), (1,0), (1,1)\}$ collapse under the quotient mapping into a single unique point on the torus manifold, verifying how relations collapse the infinite syntactic coordinates."
      },
      ja: {
        narrative: "数学は、自由生成（構文）と商化（意味論）の双対サイクル「のみ」で構成されています。トポロジーにおいては、平坦で制約のない2次元座標（自由な構文生成）をコンパクトな多様体へと折り畳むことでこれが視覚化されます。対向する境界を $x \\sim x+1$ および $y \\sim y+1$ という同値関係で商化することにより、無限の境界が崩壊します。平坦な構文シートだったものが意味的な3次元トーラス多様体へと商化され、形状が自由生成された空間を商化することの商意味的帰結であることが示されます。",
        rigor: "数学において、自由生成と商化による構造の定義は、公式に「生成元と関係式」（あるいは「プレゼンテーション」）による定義として知られています。自由生成フェーズでは、制約のない座標構文を表す位相空間 $X = [0, 1] \\times [0, 1] \\subset \\mathbb{R}^2$ を構築します。商化フェーズでは、接着関係式としてすべての $x, y \\in [0, 1]$ に対する $(x, 0) \\sim (x, 1)$ および $(0, y) \\sim (1, y)$ を定義します。$X/\\sim$ 上の商位相は境界を崩壊させ、このプレゼンテーションはトーラス $S^1 \\times S^1$ と同相な商空間を構築し、トポロジカル多様体が自由生成された構文座標の意味的商空間であることを証明します。",
        history: "幾何学の歴史は、形状が固有の計量ではなく、自由生成された構文空間の意味的商であることを示しています。アンリ・ポアンカレは、多様体が境界関係式を介したプレゼンテーションで定義できることを示し、数学を硬直した座標構文から大域的な意味論へとシフトさせました。この歴史的転換は、数学的空間が「座標の自由生成（構文）とその境界の商化（意味）」という双対サイクルのみから生まれるという核心的哲学を裏付けています。",
        exercises: "1. 自由生成された2Dシート内の座標 $(0, 0.5)$ を指定し、意味的トーラスに崩壊させる商関係 $x \\sim x+1$ の下で接着されるもう一方の座標を求めてください。\n2. 平坦なシートの4つのコーナー $\{(0,0), (0,1), (1,0), (1,1)\}$ が、商写像の下でトーラス多様体上の唯一の単一の点へと崩壊することを証明し、関係式がどのように座標の構文を崩壊させるかを検証してください。"
      }
    }[language];
  }, [language]);

  // TTS States
  const [activeSpeechText, setActiveSpeechText] = useState<string | null>(null);
  const [voices, setVoices] = useState<SpeechSynthesisVoice[]>([]);
  const [selectedVoiceName, setSelectedVoiceName] = useState<string>('');
  const [currentCharIndex, setCurrentCharIndex] = useState<number>(-1);
  const [speedMultiplier, setSpeedMultiplier] = useState<number>(1.0);
  const [isPaused, setIsPaused] = useState<boolean>(false);
  const [activeTab, setActiveTab] = useState<'narrative' | 'rigor' | 'history' | 'exercises'>('narrative');

  // Load voices dynamically based on active language selection
  useEffect(() => {
    if (typeof window === 'undefined' || !('speechSynthesis' in window)) return;

    const loadVoices = () => {
      const allVoices = window.speechSynthesis.getVoices();
      const langPrefix = language === 'ja' ? 'ja' : 'en';
      const filteredVoices = allVoices.filter(v => v.lang.startsWith(langPrefix));
      setVoices(filteredVoices);

      const scoredVoices = filteredVoices.map(v => {
        let score = 0;
        const nameLower = v.name.toLowerCase();
        const langLower = v.lang.toLowerCase();

        if (language === 'en') {
          if (langLower.includes('en-us') || langLower.includes('en_us')) score += 100;
          if (nameLower.includes('natural') || nameLower.includes('neural') || nameLower.includes('online')) score += 50;
          if (nameLower.includes('google') || nameLower.includes('microsoft') || nameLower.includes('apple')) score += 30;
        } else {
          if (nameLower.includes('google') || nameLower.includes('natural') || nameLower.includes('neural') || nameLower.includes('online')) score += 50;
          if (nameLower.includes('sayaka') || nameLower.includes('haruka')) score += 20;
        }
        return { voice: v, score };
      });

      scoredVoices.sort((a, b) => b.score - a.score);
      const bestVoice = scoredVoices[0]?.voice || filteredVoices[0];

      if (bestVoice) {
        setSelectedVoiceName(bestVoice.name);
      }
    };

    loadVoices();
    window.speechSynthesis.onvoiceschanged = loadVoices;
  }, [language]);

  // Stop speech when active tab or language changes
  useEffect(() => {
    stopSpeechComplete();
  }, [activeTab, language]);

  // Hot-reload speed multiplier mid-speech
  useEffect(() => {
    if (activeSpeechText) {
      const activeIdx = currentCharIndex >= 0 ? currentCharIndex : 0;
      startSpeech(activeSpeechText, activeIdx);
    }
  }, [speedMultiplier]);

  useEffect(() => {
    return () => {
      if (typeof window !== 'undefined' && 'speechSynthesis' in window) {
        window.speechSynthesis.cancel();
      }
    };
  }, []);

  const stopSpeechComplete = () => {
    if (typeof window !== 'undefined' && 'speechSynthesis' in window) {
      window.speechSynthesis.cancel();
    }
    if (activeUtteranceRef) {
      activeUtteranceRef = null;
    }
    setActiveSpeechText(null);
    setCurrentCharIndex(-1);
    setIsPaused(false);
  };

  const startSpeech = (text: string, startIndex: number) => {
    if (typeof window === 'undefined' || !('speechSynthesis' in window)) return;
    window.speechSynthesis.cancel();
    
    setTimeout(() => {
      const sliceText = text.substring(startIndex);
      if (!sliceText.trim()) {
        stopSpeechComplete();
        return;
      }

      const cleanText = ", " + sliceText.replace(/[\$\{\}\[\]\(\)⊣→≅↦]/g, ' '); 
      const utterance = new SpeechSynthesisUtterance(cleanText);
      activeUtteranceRef = utterance; // Prevent garbage collection
      
      const voice = voices.find(v => v.name === selectedVoiceName);
      if (voice) {
        utterance.voice = voice;
      }

      const baseRate = language === 'ja' ? 0.95 : 0.92;
      utterance.rate = baseRate * speedMultiplier;
      utterance.pitch = 1.0;

      utterance.onboundary = (event) => {
        if (event.name === 'word') {
          const adjustedCharIdx = event.charIndex - 2;
          if (adjustedCharIdx >= 0) {
            const currentIdx = startIndex + adjustedCharIdx;
            setCurrentCharIndex(currentIdx);
            
            // Extract the word that is currently being spoken
            const spokenWord = getWordAtCharIndex(text, currentIdx);
            if (spokenWord) {
              handleSpeechTrigger(spokenWord);
            }
          }
        }
      };

      utterance.onend = () => {
        setTimeout(() => {
          if (!window.speechSynthesis.speaking && !window.speechSynthesis.pending) {
            stopSpeechComplete();
          }
        }, 60);
      };

      utterance.onerror = () => {
        stopSpeechComplete();
      };

      window.speechSynthesis.speak(utterance);
      setActiveSpeechText(text);
      setIsPaused(false);
      setCurrentCharIndex(startIndex);
    }, 100);
  };

  const speakCurrentStop = (text: string) => {
    if (typeof window === 'undefined' || !('speechSynthesis' in window)) return;

    if (activeSpeechText === text) {
      if (isPaused) {
        window.speechSynthesis.resume();
        setIsPaused(false);
      } else {
        window.speechSynthesis.pause();
        setIsPaused(true);
      }
    } else {
      startSpeech(text, 0);
    }
  };

  const handleSeek = (direction: 'fwd' | 'rwd') => {
    if (!activeSpeechText) return;
    const words = getSpokenWords(activeSpeechText, language);
    if (words.length === 0) return;

    let currentWordIdx = words.findIndex(
      w => currentCharIndex >= w.start && currentCharIndex <= w.end
    );
    if (currentWordIdx === -1) {
      currentWordIdx = words.findIndex(w => w.start > currentCharIndex);
      if (currentWordIdx === -1) currentWordIdx = words.length - 1;
    }

    const wordSkip = 4;
    let targetWordIdx = direction === 'fwd' 
      ? Math.min(words.length - 1, currentWordIdx + wordSkip) 
      : Math.max(0, currentWordIdx - wordSkip);

    const targetWord = words[targetWordIdx];
    startSpeech(activeSpeechText, targetWord.start);
  };

  const getSpokenWords = (text: string, lang: 'en' | 'ja'): SpokenWord[] => {
    const words: SpokenWord[] = [];
    if (lang === 'ja') {
      for (let i = 0; i < text.length; i++) {
        words.push({ text: text[i], start: i, end: i + 1 });
      }
    } else {
      const wordRegex = /[a-zA-Z0-9'’⊣→≅↦ηε\(\)\{\}\-\:\,]+/g;
      let match;
      while ((match = wordRegex.exec(text)) !== null) {
        words.push({
          text: match[0],
          start: match.index,
          end: match.index + match[0].length
        });
      }
    }
    return words;
  };

  const getWordAtCharIndex = (text: string, charIdx: number): string | null => {
    const words = getSpokenWords(text, language);
    const match = words.find(w => charIdx >= w.start && charIdx < w.end);
    return match ? match.text : null;
  };

  const handleSpeechTrigger = (word: string) => {
    const w = word.toLowerCase();
    if (w.includes('cylinder') || w.includes('円柱')) {
      setGluingStage(1.0);
      setIsFolding(false);
    } else if (w.includes('torus') || w.includes('トーラス')) {
      setGluingStage(2.0);
      setIsFolding(false);
    } else if (w.includes('flat') || w.includes('sheet') || w.includes('euclidean') || w.includes('平ら') || w.includes('平面')) {
      setGluingStage(0.0);
      setIsFolding(false);
    } else if (w.includes('folding') || w.includes('gluing') || w.includes('collapse') || w.includes('折り畳み') || w.includes('接着') || w.includes('縮退')) {
      setIsFolding(true);
    }
  };

  const renderHighlightedText = (text: string) => {
    const words = getSpokenWords(text, language);
    let result: React.ReactNode[] = [];
    let lastIdx = 0;
    
    words.forEach((w, idx) => {
      if (w.start > lastIdx) {
        result.push(text.substring(lastIdx, w.start));
      }
      
      const isCurrent = currentCharIndex >= w.start && currentCharIndex < w.end;
      result.push(
        <span 
          key={idx} 
          className={isCurrent ? "word-highlight" : "word-normal"}
          onClick={() => startSpeech(text, w.start)}
          title={language === 'en' ? 'Click to play from here' : 'ここから再生'}
        >
          {w.text}
        </span>
      );
      lastIdx = w.end;
    });
    
    if (lastIdx < text.length) {
      result.push(text.substring(lastIdx));
    }
    
    return result;
  };

  // Visualizer States
  const [gluingStage, setGluingStage] = useState<number>(0.0); // t from 0 to 2
  const [activePoint, setActivePoint] = useState<Point2D | null>({ x: 0.5, y: 0.5 });
  const [isFolding, setIsFolding] = useState<boolean>(false);
  const [isRotating, setIsRotating] = useState<boolean>(true);

  // Rotation angles (rx = pitch/X-rotation, ry = yaw/Y-rotation, rz = roll/Z-rotation)
  // Default values to give a nice 3D view on startup
  const [rotationAngle, setRotationAngle] = useState({
    x: -0.4,
    y: 0.6,
    z: 0.0,
  });

  const [isDragging, setIsDragging] = useState<boolean>(false);
  const dragStart = useRef({ x: 0, y: 0 });

  // Animation Loop (auto-rotation and auto-folding)
  useEffect(() => {
    let lastTime = performance.now();
    let frameId: number;

    const loop = (time: number) => {
      const delta = (time - lastTime) / 1000; // in seconds
      lastTime = time;

      if (isFolding) {
        setGluingStage((prev) => {
          let next = prev + delta * 0.35; // take about 5.7s for full fold cycle
          if (next >= 2.0) {
            next = 0.0;
          }
          return next;
        });
      }

      if (isRotating) {
        setRotationAngle((prev) => ({
          x: prev.x,
          y: (prev.y + delta * 0.25) % (2 * Math.PI),
          z: (prev.z + delta * 0.1) % (2 * Math.PI),
        }));
      }

      frameId = requestAnimationFrame(loop);
    };

    frameId = requestAnimationFrame(loop);
    return () => cancelAnimationFrame(frameId);
  }, [isFolding, isRotating]);

  // Snapping and placement logic for 2D representation
  const handle2DPointer = (
    e: React.MouseEvent<SVGSVGElement> | React.TouchEvent<SVGSVGElement>
  ) => {
    const rect = e.currentTarget.getBoundingClientRect();
    let clientX = 0;
    let clientY = 0;

    if ('touches' in e) {
      if (e.touches.length === 0) return;
      clientX = e.touches[0].clientX;
      clientY = e.touches[0].clientY;
    } else {
      clientX = e.clientX;
      clientY = e.clientY;
    }

    // 2D sheet is placed at (20, 20) with width=240, height=240 in SVG
    const px = clientX - rect.left - 20;
    const py = clientY - rect.top - 20;

    // Clamp coordinates to the sheet area [0, 240]
    const cx = Math.max(0, Math.min(240, px));
    const cy = Math.max(0, Math.min(240, py));

    let x = cx / 240;
    let y = cy / 240;

    // Boundary Snapping: if close to boundaries, snap to edges to help show equivalence class
    const SNAP_THRESHOLD_PX = 8;
    if (cx < SNAP_THRESHOLD_PX) {
      x = 0;
    } else if (cx > 240 - SNAP_THRESHOLD_PX) {
      x = 1;
    }

    if (cy < SNAP_THRESHOLD_PX) {
      y = 0;
    } else if (cy > 240 - SNAP_THRESHOLD_PX) {
      y = 1;
    }

    setActivePoint({ x, y });
  };

  // Drag-to-rotate handlers for the 3D model
  const handleMouseDown = (e: React.MouseEvent) => {
    setIsDragging(true);
    dragStart.current = { x: e.clientX, y: e.clientY };
  };

  const handleMouseMove = (e: React.MouseEvent) => {
    if (!isDragging) return;
    const dx = e.clientX - dragStart.current.x;
    const dy = e.clientY - dragStart.current.y;
    dragStart.current = { x: e.clientX, y: e.clientY };

    setRotationAngle((prev) => ({
      x: (prev.x + dy * 0.007) % (2 * Math.PI),
      y: (prev.y + dx * 0.007) % (2 * Math.PI),
      z: prev.z,
    }));
  };

  const handleMouseUp = () => {
    setIsDragging(false);
  };

  const handleTouchStart = (e: React.TouchEvent) => {
    if (e.touches.length === 0) return;
    setIsDragging(true);
    dragStart.current = { x: e.touches[0].clientX, y: e.touches[0].clientY };
  };

  const handleTouchMove = (e: React.TouchEvent) => {
    if (!isDragging || e.touches.length === 0) return;
    const dx = e.touches[0].clientX - dragStart.current.x;
    const dy = e.touches[0].clientY - dragStart.current.y;
    dragStart.current = { x: e.touches[0].clientX, y: e.touches[0].clientY };

    setRotationAngle((prev) => ({
      x: (prev.x + dy * 0.007) % (2 * Math.PI),
      y: (prev.y + dx * 0.007) % (2 * Math.PI),
      z: prev.z,
    }));
  };

  // Convert normalized [0, 1] points to 2D SVG canvas [20, 260] coords
  const toSVGCoords = (x: number, y: number) => {
    return {
      cx: 20 + x * 240,
      cy: 20 + y * 240,
    };
  };

  // Compute Equivalence Class on the Torus
  // (x, y) coordinates glued on borders: (x, 0) ~ (x, 1) and (0, y) ~ (1, y)
  const getEquivalenceClass = (x: number, y: number): Point2D[] => {
    const isLeft = x === 0;
    const isRight = x === 1;
    const isTop = y === 0;
    const isBottom = y === 1;

    // Corner cases: all 4 corners represent the exact same quotient point
    if ((isLeft || isRight) && (isTop || isBottom)) {
      return [
        { x: 0, y: 0 },
        { x: 1, y: 0 },
        { x: 0, y: 1 },
        { x: 1, y: 1 },
      ];
    }
    // Left/Right boundaries glue to each other
    if (isLeft || isRight) {
      return [
        { x: 0, y },
        { x: 1, y },
      ];
    }
    // Top/Bottom boundaries glue to each other
    if (isTop || isBottom) {
      return [
        { x, y: 0 },
        { x, y: 1 },
      ];
    }
    // Interior points have a singleton equivalence class
    return [{ x, y }];
  };

  // Render equivalence connection lines on 2D sheet
  const renderEquivalenceLines = () => {
    if (!activePoint) return null;
    const { x, y } = activePoint;

    const isLeft = x === 0;
    const isRight = x === 1;
    const isTop = y === 0;
    const isBottom = y === 1;

    const leftX = 20;
    const rightX = 260;
    const topY = 20;
    const bottomY = 260;

    const curX = 20 + x * 240;
    const curY = 20 + y * 240;

    if ((isLeft || isRight) && (isTop || isBottom)) {
      return (
        <>
          <line x1={leftX} y1={topY} x2={rightX} y2={topY} stroke="#d4af37" strokeDasharray="3 3" strokeWidth="1.5" />
          <line x1={leftX} y1={bottomY} x2={rightX} y2={bottomY} stroke="#d4af37" strokeDasharray="3 3" strokeWidth="1.5" />
          <line x1={leftX} y1={topY} x2={leftX} y2={bottomY} stroke="#38bdf8" strokeDasharray="3 3" strokeWidth="1.5" />
          <line x1={rightX} y1={topY} x2={rightX} y2={bottomY} stroke="#38bdf8" strokeDasharray="3 3" strokeWidth="1.5" />
        </>
      );
    }

    if (isLeft || isRight) {
      return (
        <line
          x1={leftX}
          y1={curY}
          x2={rightX}
          y2={curY}
          stroke="#38bdf8"
          strokeDasharray="4 4"
          strokeWidth="1.5"
          opacity="0.8"
        />
      );
    }

    if (isTop || isBottom) {
      return (
        <line
          x1={curX}
          y1={topY}
          x2={curX}
          y2={bottomY}
          stroke="#d4af37"
          strokeDasharray="4 4"
          strokeWidth="1.5"
          opacity="0.8"
        />
      );
    }

    return null;
  };

  // Math: 3D coordinates calculation with interpolation
  const getInterpolatedCoords = (x: number, y: number, t: number) => {
    // 1. Flat Sheet
    const xFlat = (x - 0.5) * 160;
    const yFlat = (y - 0.5) * 160;
    const zFlat = 0;

    // 2. Cylinder
    const rCyl = 160 / (2 * Math.PI);
    const theta = 2 * Math.PI * y - Math.PI;
    const xCyl = rCyl * Math.cos(theta);
    const yCyl = (x - 0.5) * 160;
    const zCyl = rCyl * Math.sin(theta);

    // 3. Torus
    const R = 160 / (2 * Math.PI);
    const r = rCyl;
    const phi = 2 * Math.PI * x - Math.PI;
    const xTor = (R + r * Math.cos(theta)) * Math.cos(phi);
    const yTor = (R + r * Math.cos(theta)) * Math.sin(phi);
    const zTor = r * Math.sin(theta);

    if (t <= 1) {
      // Interpolate Flat -> Cylinder
      const s = t;
      return {
        x: (1 - s) * xFlat + s * xCyl,
        y: (1 - s) * yFlat + s * yCyl,
        z: (1 - s) * zFlat + s * zCyl,
      };
    } else {
      // Interpolate Cylinder -> Torus
      const s = t - 1;
      return {
        x: (1 - s) * xCyl + s * xTor,
        y: (1 - s) * yCyl + s * yTor,
        z: (1 - s) * zCyl + s * zTor,
      };
    }
  };

  // Math: Rotate point in 3D
  const rotate3D = (
    x: number,
    y: number,
    z: number,
    rx: number,
    ry: number,
    rz: number
  ) => {
    // Rotate around X-axis
    const x1 = x;
    const y1 = y * Math.cos(rx) - z * Math.sin(rx);
    const z1 = y * Math.sin(rx) + z * Math.cos(rx);

    // Rotate around Y-axis
    const x2 = x1 * Math.cos(ry) + z1 * Math.sin(ry);
    const y2 = y1;
    const z2 = -x1 * Math.sin(ry) + z1 * Math.cos(ry);

    // Rotate around Z-axis
    const x3 = x2 * Math.cos(rz) - y2 * Math.sin(rz);
    const y3 = x2 * Math.sin(rz) + y2 * Math.cos(rz);
    const z3 = z2;

    return { x: x3, y: y3, z: z3 };
  };

  // Math: 3D perspective projection
  const project = (x: number, y: number, z: number) => {
    const D = 320; // Camera distance
    const scale = 2.0; // Viewport scaling multiplier
    const factor = D / (D - z);
    return {
      u: x * factor * scale,
      v: y * factor * scale,
    };
  };

  // Build and depth-sort 3D elements (grid lines + points)
  const projectedItems = useMemo(() => {
    const items: ProjectedItem[] = [];

    const stepsX = 13; // number of longitudinal grid lines
    const stepsY = 13; // number of latitudinal grid lines
    const sampleSteps = 40; // smoothness of lines

    // 1. Longitudinal grid lines (constant x, varying y)
    for (let i = 0; i < stepsX; i++) {
      const x = i / (stepsX - 1);
      const isLeft = i === 0;
      const isRight = i === stepsX - 1;

      let color = 'rgba(192, 132, 252, 0.22)';
      let strokeWidth = 1.0;
      if (isLeft || isRight) {
        color = '#38bdf8'; // Cyan boundary B
        strokeWidth = 2.2;
      }

      const pts: { u: number; v: number; zRot: number }[] = [];
      for (let j = 0; j < sampleSteps; j++) {
        const y = j / (sampleSteps - 1);
        const coords = getInterpolatedCoords(x, y, gluingStage);
        const rot = rotate3D(coords.x, coords.y, coords.z, rotationAngle.x, rotationAngle.y, rotationAngle.z);
        const proj = project(rot.x, rot.y, rot.z);
        pts.push({ u: proj.u, v: proj.v, zRot: rot.z });
      }

      const avgDepth = pts.reduce((sum, p) => sum + p.zRot, 0) / pts.length;
      let pathData = `M ${pts[0].u.toFixed(1)} ${pts[0].v.toFixed(1)}`;
      for (let j = 1; j < pts.length; j++) {
        pathData += ` L ${pts[j].u.toFixed(1)} ${pts[j].v.toFixed(1)}`;
      }

      items.push({
        type: 'grid-line',
        id: `grid-x-${i}`,
        pathData,
        color,
        strokeWidth,
        opacity: (isLeft || isRight) ? 0.95 : 0.45,
        depth: avgDepth,
      });
    }

    // 2. Latitudinal grid lines (constant y, varying x)
    for (let i = 0; i < stepsY; i++) {
      const y = i / (stepsY - 1);
      const isTop = i === 0;
      const isBottom = i === stepsY - 1;

      let color = 'rgba(192, 132, 252, 0.22)';
      let strokeWidth = 1.0;
      if (isTop || isBottom) {
        color = '#d4af37'; // Gold boundary A
        strokeWidth = 2.2;
      }

      const pts: { u: number; v: number; zRot: number }[] = [];
      for (let j = 0; j < sampleSteps; j++) {
        const x = j / (sampleSteps - 1);
        const coords = getInterpolatedCoords(x, y, gluingStage);
        const rot = rotate3D(coords.x, coords.y, coords.z, rotationAngle.x, rotationAngle.y, rotationAngle.z);
        const proj = project(rot.x, rot.y, rot.z);
        pts.push({ u: proj.u, v: proj.v, zRot: rot.z });
      }

      const avgDepth = pts.reduce((sum, p) => sum + p.zRot, 0) / pts.length;
      let pathData = `M ${pts[0].u.toFixed(1)} ${pts[0].v.toFixed(1)}`;
      for (let j = 1; j < pts.length; j++) {
        pathData += ` L ${pts[j].u.toFixed(1)} ${pts[j].v.toFixed(1)}`;
      }

      items.push({
        type: 'grid-line',
        id: `grid-y-${i}`,
        pathData,
        color,
        strokeWidth,
        opacity: (isTop || isBottom) ? 0.95 : 0.45,
        depth: avgDepth,
      });
    }

    // 3. Highlighted equivalent points projected in 3D
    if (activePoint) {
      const equivPoints = getEquivalenceClass(activePoint.x, activePoint.y);
      equivPoints.forEach((pt, idx) => {
        const coords = getInterpolatedCoords(pt.x, pt.y, gluingStage);
        const rot = rotate3D(coords.x, coords.y, coords.z, rotationAngle.x, rotationAngle.y, rotationAngle.z);
        const proj = project(rot.x, rot.y, rot.z);

        items.push({
          type: 'point',
          id: `point-equiv-${idx}`,
          cx: proj.u,
          cy: proj.v,
          color: '#d4af37',
          depth: rot.z,
        });
      });
    }

    // Sort items by depth (ascending: painter's algorithm renders back elements first)
    items.sort((a, b) => a.depth - b.depth);

    return items;
  }, [gluingStage, rotationAngle, activePoint]);

  // Inject stylesheet for keyframe animations
  const styleSheet = `
    @keyframes pulse-2d {
      0% { r: 4px; opacity: 0.9; }
      100% { r: 14px; opacity: 0; }
    }
    @keyframes pulse-3d {
      0% { r: 5px; opacity: 0.9; }
      100% { r: 18px; opacity: 0; }
    }
    .pulse-circle-2d {
      animation: pulse-2d 1.6s cubic-bezier(0.25, 0, 0, 1) infinite;
    }
    .pulse-circle-3d {
      animation: pulse-3d 1.6s cubic-bezier(0.25, 0, 0, 1) infinite;
    }
    .slider-stage-label {
      cursor: pointer;
      padding: 2px 6px;
      border-radius: 4px;
      transition: all 0.2s ease;
    }
    .slider-stage-label:hover {
      background: rgba(255, 255, 255, 0.05);
      color: var(--primary);
    }
  `;

  return (
    <div className="visualizer-container animate-pop-in">
      <style dangerouslySetInnerHTML={{ __html: styleSheet }} />

      <div className="exhibit-grid">
        {/* Left Side: Placard & Interactive 2D Sheet */}
        <div className="placard-panel">
          {!onlyVisualizer && (
            <div>
              <div className="placard-header">
                <BookOpen size={12} />
                <span>{t.roomTitle}</span>
              </div>
              <h2 className="placard-title">{t.title}</h2>
              <h3 className="placard-subtitle">{t.subtitle}</h3>

              {/* Tab Selector */}
              <div className="placard-tabs" style={{ display: 'flex', gap: '0.35rem', marginBottom: '1.25rem', borderBottom: '1px solid rgba(255,255,255,0.08)', paddingBottom: '0.5rem' }}>
                {(['narrative', 'rigor', 'history', 'exercises'] as const).map(tab => (
                  <button
                    key={tab}
                    onClick={() => setActiveTab(tab)}
                    className={`btn-lang ${activeTab === tab ? 'active' : ''}`}
                    style={{ fontSize: '0.68rem', padding: '4px 8px', textTransform: 'uppercase', letterSpacing: '0.05em' }}
                  >
                    {tab === 'narrative' ? (language === 'en' ? 'Narrative' : '叙事') :
                     tab === 'rigor' ? (language === 'en' ? 'Mathematical Rigor' : '数学的厳密性') :
                     tab === 'history' ? (language === 'en' ? 'Historical Context' : '歴史的背景') :
                     (language === 'en' ? 'Exercises' : '演習')}
                  </button>
                ))}
              </div>

              {/* Audio Guide Device Widget */}
              <div className="audio-guide-player" style={{ marginBottom: '1.25rem', padding: '0.6rem 1rem', gap: '1rem', borderRadius: '0.75rem' }}>
                <div className="device-info">
                  <div className="device-screen" style={{ width: '2rem', height: '2rem', borderRadius: '0.5rem', fontSize: '0.55rem' }}>
                    {activeSpeechText ? 'ON' : 'OFF'}
                  </div>
                  <div className="device-meta">
                    <h4 style={{ fontSize: '0.55rem' }}>{language === 'en' ? 'Audio Companion' : '音声ガイド'}</h4>
                    <p style={{ fontSize: '0.5rem' }}>{activeTab.toUpperCase()}</p>
                  </div>
                </div>

                <div className="audio-controls-group" style={{ gap: '0.5rem', padding: '0.2rem 0.75rem' }}>
                  {voices.length > 0 && (
                    <select
                      value={selectedVoiceName}
                      onChange={(e) => setSelectedVoiceName(e.target.value)}
                      className="input-text"
                      style={{ 
                        width: '80px', 
                        fontSize: '0.55rem', 
                        padding: '1px 2px', 
                        height: '20px', 
                        background: 'rgba(0,0,0,0.5)',
                        border: '1px solid rgba(212,175,55,0.3)',
                        color: 'var(--primary)',
                        cursor: 'pointer',
                        borderRadius: '4px'
                      }}
                    >
                      {voices.map((v, i) => (
                        <option key={i} value={v.name} style={{ background: '#0b0f19', color: '#fff' }}>
                          {v.name.replace('Microsoft', 'MS').replace('Google', 'G').replace('日本語', 'JP')}
                        </option>
                      ))}
                    </select>
                  )}

                  <select
                    value={speedMultiplier.toString()}
                    onChange={(e) => setSpeedMultiplier(parseFloat(e.target.value))}
                    className="input-text"
                    style={{ 
                      width: '48px', 
                      fontSize: '0.55rem', 
                      padding: '1px 2px', 
                      height: '20px', 
                      background: 'rgba(0,0,0,0.5)',
                      border: '1px solid rgba(212,175,55,0.3)',
                      color: 'var(--primary)',
                      cursor: 'pointer',
                      borderRadius: '4px'
                    }}
                  >
                    <option value="1">1.0x</option>
                    <option value="1.25">1.2x</option>
                    <option value="1.5">1.5x</option>
                    <option value="2">2.0x</option>
                  </select>

                  <div style={{ display: 'flex', alignItems: 'center', gap: '0.25rem' }}>
                    <button
                      onClick={() => handleSeek('rwd')}
                      disabled={!activeSpeechText}
                      className="btn btn-outline"
                      style={{ width: '20px', height: '20px', padding: '0', display: 'flex', alignItems: 'center', justifyContent: 'center' }}
                    >
                      <Rewind size={8} />
                    </button>

                    <button
                      onClick={() => speakCurrentStop(tabContent[activeTab])}
                      className="btn btn-primary"
                      style={{ width: '22px', height: '22px', padding: '0', display: 'flex', alignItems: 'center', justifyContent: 'center', borderRadius: '50%' }}
                    >
                      {activeSpeechText && !isPaused ? <Pause size={8} /> : <Play size={8} />}
                    </button>

                    <button
                      onClick={() => handleSeek('fwd')}
                      disabled={!activeSpeechText}
                      className="btn btn-outline"
                      style={{ width: '20px', height: '20px', padding: '0', display: 'flex', alignItems: 'center', justifyContent: 'center' }}
                    >
                      <FastForward size={8} />
                    </button>

                    <button
                      onClick={stopSpeechComplete}
                      disabled={!activeSpeechText}
                      className="btn btn-outline"
                      style={{ width: '20px', height: '20px', padding: '0', display: 'flex', alignItems: 'center', justifyContent: 'center', borderColor: activeSpeechText ? 'var(--error)' : 'rgba(255,255,255,0.1)' }}
                    >
                      <Square size={8} style={{ fill: activeSpeechText ? 'var(--error)' : 'none', color: activeSpeechText ? 'var(--error)' : 'currentColor' }} />
                    </button>
                  </div>
                </div>
              </div>

              <div className="placard-text" style={{ fontSize: '0.85rem', lineHeight: '1.6', color: 'var(--text-muted)', minHeight: '140px', whiteSpace: 'pre-line' }}>
                <p>{renderHighlightedText(tabContent[activeTab])}</p>
              </div>
            </div>
          )}

          {/* Interactive 2D Sheet representation */}
          <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', marginTop: '1.25rem', gap: '0.75rem' }}>
            <div style={{ fontSize: '0.7rem', textTransform: 'uppercase', letterSpacing: '0.12em', color: 'var(--primary)', fontWeight: 'bold' }}>
              {t.instruction}
            </div>

            <div style={{ position: 'relative', background: 'rgba(10, 15, 30, 0.45)', borderRadius: '1rem', border: '1px solid rgba(212,175,55,0.15)', padding: '0.75rem' }}>
              <svg
                width="280"
                height="280"
                viewBox="0 0 280 280"
                style={{ cursor: 'crosshair', touchAction: 'none' }}
                onMouseMove={handle2DPointer}
                onMouseDown={handle2DPointer}
                onTouchStart={handle2DPointer}
                onTouchMove={handle2DPointer}
              >
                {/* 2D Sheet surface */}
                <rect x="20" y="20" width="240" height="240" fill="rgba(15, 23, 42, 0.6)" stroke="rgba(255,255,255,0.03)" />
                
                {/* 2D Grid markings */}
                {Array.from({ length: 9 }).map((_, i) => {
                  const pos = 20 + (i + 1) * 24;
                  return (
                    <g key={i}>
                      <line x1={pos} y1="20" x2={pos} y2="260" stroke="rgba(255,255,255,0.03)" strokeWidth="1" />
                      <line x1="20" y1={pos} x2="260" y2={pos} stroke="rgba(255,255,255,0.03)" strokeWidth="1" />
                    </g>
                  );
                })}

                {/* Dashed lines connecting equivalence classes */}
                {renderEquivalenceLines()}

                {/* Boundaries */}
                {/* Top: A (Gold) */}
                <line x1="20" y1="20" x2="260" y2="20" stroke="#d4af37" strokeWidth="3" />
                {/* Bottom: A (Gold) */}
                <line x1="20" y1="260" x2="260" y2="260" stroke="#d4af37" strokeWidth="3" />
                {/* Left: B (Cyan) */}
                <line x1="20" y1="20" x2="20" y2="260" stroke="#38bdf8" strokeWidth="3" />
                {/* Right: B (Cyan) */}
                <line x1="260" y1="20" x2="260" y2="260" stroke="#38bdf8" strokeWidth="3" />

                {/* Gluing Direction Arrowheads */}
                {/* Top/Bottom pointing right */}
                <polygon points="136,16 144,20 136,24" fill="#d4af37" />
                <polygon points="136,256 144,260 136,264" fill="#d4af37" />
                {/* Left/Right pointing up */}
                <polygon points="16,144 20,136 24,144" fill="#38bdf8" />
                <polygon points="256,144 260,136 264,144" fill="#38bdf8" />

                {/* Boundary Labels */}
                <text x="150" y="14" fill="#d4af37" fontSize="10" fontWeight="bold" textAnchor="middle">A</text>
                <text x="150" y="274" fill="#d4af37" fontSize="10" fontWeight="bold" textAnchor="middle">A</text>
                <text x="8" y="144" fill="#38bdf8" fontSize="10" fontWeight="bold" textAnchor="middle">B</text>
                <text x="272" y="144" fill="#38bdf8" fontSize="10" fontWeight="bold" textAnchor="middle">B</text>

                {/* Equivalence points render */}
                {activePoint && getEquivalenceClass(activePoint.x, activePoint.y).map((pt, idx) => {
                  const { cx, cy } = toSVGCoords(pt.x, pt.y);
                  return (
                    <g key={idx}>
                      <circle cx={cx} cy={cy} className="pulse-circle-2d" fill="#d4af37" />
                      <circle cx={cx} cy={cy} r="4.5" fill="#d4af37" stroke="#ffffff" strokeWidth="1" />
                    </g>
                  );
                })}
              </svg>
            </div>

            {/* Boundary Legend */}
            <div style={{ display: 'flex', flexDirection: 'column', gap: '0.35rem', fontSize: '0.68rem', color: 'var(--text-muted)', width: '100%', maxWidth: '280px' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                <div style={{ width: '14px', height: '3px', background: '#d4af37' }}></div>
                <span>{t.boundaryA}</span>
              </div>
              <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                <div style={{ width: '14px', height: '3px', background: '#38bdf8' }}></div>
                <span>{t.boundaryB}</span>
              </div>
              {activePoint && (
                <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginTop: '0.2rem', color: 'var(--primary)' }}>
                  <span style={{ width: '6px', height: '6px', borderRadius: '50%', background: '#d4af37', display: 'inline-block' }}></span>
                  <span>
                    {t.equivalenceClass}: {getEquivalenceClass(activePoint.x, activePoint.y).length} {language === 'en' ? 'point(s)' : '個の点の集合'}
                  </span>
                </div>
              )}
            </div>
          </div>

          {!onlyVisualizer && (
            <div className="placard-footer">
              <span>ONTOLOGY MUSEUM</span>
              <span>ROOM 03</span>
            </div>
          )}
        </div>

        {/* Right Side: Kiosk (3D Model Projection Viewer) */}
        <div className="kiosk-panel" style={{ display: 'flex', flexDirection: 'column', justifyContent: 'space-between' }}>
          
          {/* Section title */}
          <div style={{ width: '100%', display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '0.5rem' }}>
            <div>
              <h4 style={{ fontSize: '0.75rem', fontWeight: 800, letterSpacing: '0.2em', color: 'var(--primary)', textTransform: 'uppercase' }}>
                {language === 'en' ? '3D Folding Transformation' : '3D折り畳み同相写像'}
              </h4>
              <p style={{ fontSize: '0.65rem', color: 'var(--text-muted)', marginTop: '0.15rem' }}>
                {t.dragPrompt}
              </p>
            </div>
          </div>

          {/* 3D SVG Projection Arena */}
          <div style={{ flexGrow: 1, width: '100%', display: 'flex', alignItems: 'center', justifyContent: 'center', minHeight: 0, padding: '0.5rem 0' }}>
            <svg
              viewBox="-250 -250 500 500"
              style={{
                width: '100%',
                height: '100%',
                maxHeight: '430px',
                background: 'radial-gradient(circle at center, rgba(16, 24, 48, 0.45) 0%, rgba(5, 7, 12, 0.88) 100%)',
                borderRadius: '1rem',
                border: '1px solid rgba(255, 255, 255, 0.04)',
                cursor: isDragging ? 'grabbing' : 'grab',
                userSelect: 'none',
                touchAction: 'none',
              }}
              onMouseDown={handleMouseDown}
              onMouseMove={handleMouseMove}
              onMouseUp={handleMouseUp}
              onMouseLeave={handleMouseUp}
              onTouchStart={handleTouchStart}
              onTouchMove={handleTouchMove}
              onTouchEnd={handleMouseUp}
            >
              {/* Depth-sorted rendering of projected elements */}
              {projectedItems.map((item) => {
                if (item.type === 'grid-line') {
                  const minDepth = -80;
                  const maxDepth = 80;
                  const normDepth = Math.max(0, Math.min(1, (item.depth - minDepth) / (maxDepth - minDepth)));
                  const opacity = item.opacity * (0.3 + 0.7 * normDepth);
                  const strokeWidth = item.strokeWidth * (0.6 + 0.8 * normDepth);

                  return (
                    <path
                      key={item.id}
                      d={item.pathData}
                      fill="none"
                      stroke={item.color}
                      strokeWidth={strokeWidth}
                      strokeOpacity={opacity}
                      style={{ transition: 'stroke 0.3s ease' }}
                    />
                  );
                } else {
                  // Projected equivalent point(s)
                  const minDepth = -80;
                  const maxDepth = 80;
                  const normDepth = Math.max(0, Math.min(1, (item.depth - minDepth) / (maxDepth - minDepth)));
                  const size = 6.0 * (0.75 + 0.55 * normDepth);
                  const opacity = 0.55 + 0.45 * normDepth;

                  return (
                    <g key={item.id}>
                      <circle
                        cx={item.cx}
                        cy={item.cy}
                        className="pulse-circle-3d"
                        fill="#d4af37"
                        fillOpacity={opacity * 0.4}
                      />
                      <circle
                        cx={item.cx}
                        cy={item.cy}
                        r={size}
                        fill="#d4af37"
                        stroke="#ffffff"
                        strokeWidth="1.2"
                        fillOpacity={opacity}
                        strokeOpacity={opacity}
                      />
                    </g>
                  );
                }
              })}
            </svg>
          </div>

          {/* Interactive Slider */}
          <div style={{ width: '100%', marginTop: '0.75rem' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '0.4rem', fontSize: '0.725rem', color: 'var(--text-muted)' }}>
              <span>{t.gluingStage}</span>
              <span style={{ color: 'var(--primary)', fontWeight: 'bold' }}>
                {gluingStage.toFixed(2)}
              </span>
            </div>
            <input
              type="range"
              min="0"
              max="2"
              step="0.01"
              value={gluingStage}
              onChange={(e) => {
                setGluingStage(parseFloat(e.target.value));
                setIsFolding(false); // Pause auto fold on user interaction
              }}
              style={{
                width: '100%',
                accentColor: 'var(--primary)',
                background: 'rgba(255, 255, 255, 0.1)',
                height: '6px',
                borderRadius: '3px',
                outline: 'none',
                cursor: 'pointer',
              }}
            />
            <div style={{ display: 'flex', justifyContent: 'space-between', marginTop: '0.25rem', fontSize: '0.65rem', color: 'var(--text-muted)' }}>
              <span
                className="slider-stage-label"
                style={{
                  color: gluingStage === 0 ? 'var(--primary)' : 'inherit',
                  fontWeight: gluingStage === 0 ? 'bold' : 'normal',
                }}
                onClick={() => {
                  setGluingStage(0);
                  setIsFolding(false);
                }}
              >
                {t.stage0}
              </span>
              <span
                className="slider-stage-label"
                style={{
                  color: gluingStage >= 0.95 && gluingStage <= 1.05 ? 'var(--primary)' : 'inherit',
                  fontWeight: gluingStage >= 0.95 && gluingStage <= 1.05 ? 'bold' : 'normal',
                }}
                onClick={() => {
                  setGluingStage(1);
                  setIsFolding(false);
                }}
              >
                {t.stage1}
              </span>
              <span
                className="slider-stage-label"
                style={{
                  color: gluingStage === 2 ? 'var(--primary)' : 'inherit',
                  fontWeight: gluingStage === 2 ? 'bold' : 'normal',
                }}
                onClick={() => {
                  setGluingStage(2);
                  setIsFolding(false);
                }}
              >
                {t.stage2}
              </span>
            </div>
          </div>

          {/* Action Control Panel */}
          <div style={{ display: 'flex', gap: '0.75rem', width: '100%', flexWrap: 'wrap', marginTop: '1rem' }}>
            <button
              className="btn btn-secondary"
              style={{ flex: '1 1 auto', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.5rem', minWidth: '120px' }}
              onClick={() => setIsFolding(!isFolding)}
            >
              {isFolding ? <Pause size={14} /> : <Play size={14} />}
              <span>{isFolding ? t.pauseFolding : t.playFolding}</span>
            </button>

            <button
              className="btn"
              style={{
                flex: '1 1 auto',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                gap: '0.5rem',
                minWidth: '120px',
                background: isRotating ? 'rgba(212, 175, 55, 0.12)' : 'rgba(56, 189, 248, 0.08)',
                border: isRotating ? '1px solid var(--primary)' : '1px solid rgba(56, 189, 248, 0.25)',
                color: isRotating ? 'var(--primary)' : 'var(--secondary)',
              }}
              onClick={() => setIsRotating(!isRotating)}
            >
              <Layers size={14} />
              <span>{t.spin}</span>
            </button>

            <button
              className="btn btn-secondary"
              style={{ flex: '1 1 auto', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.5rem', minWidth: '100px' }}
              onClick={() => setActivePoint(null)}
            >
              <RefreshCw size={14} />
              <span>{t.reset}</span>
            </button>
          </div>

        </div>
      </div>
    </div>
  );
}
