import type { RoomData } from './curriculumData';

export const roomsPart1: Record<number, RoomData> = {
  1: {
    id: 1,
    nameEn: "Hall I: The Ontological Cycle",
    nameJa: "第I室：存在論的サイクル",
    thesisEn: "Introduction to the dual cycle of Syntax (Generators) vs. Semantics (Relations).",
    thesisJa: "構文（生成元）と意味論（関係式）の双対的サイクルの導入。",
    en: {
      narrative: "Welcome to the Ontological Cycle. At its ultimate bedrock, mathematics is not the static study of numbers or shapes, but a dynamic, cyclical dialogue between two fundamental cognitive operations: Free Generation and Quotienting. The human mind first projects raw symbols, variables, and syntax trees into the void without constraint—a process of pure syntax creation (Free Generation). It then folds, identifies, and collapses these terms under equations (relations) to resolve their semantics, mapping them to real-world experience (Quotienting). Every mathematical structure is born of this simple cognitive loop, demonstrating how infinite structural potential is bound into functional meaning.",
      rigor: "In formal algebraic terms, this cycle is modeled as a presentation by generators and relations. Given a set of raw elements $X$ (generators) and a signature $\\Sigma$ of operations, we construct the free $\\Sigma$-algebra $F(X)$ containing all possible syntactic terms. We then define a set of relations $R \\subseteq F(X) \\times F(X)$ representing equations we wish to force. The quotient structure $F(X)/\\langle R \\rangle$ is the initial algebraic structure satisfying these relations. Category-theoretically, it is formalized as the coequalizer in the category of $\\Sigma$-algebras of the parallel pair of homomorphisms $p_1, p_2: F(R) \\rightrightarrows F(X)$ extending the projection maps of the relation $R$. The quotient map $\\pi: F(X) \\to F(X)/\\langle R \\rangle$ is the coequalizer morphism, collapsing the infinite free syntax into the minimal structure satisfying the relations.",
      history: "\"The limits of my language mean the limits of my world.\" — Ludwig Wittgenstein, *Tractatus Logico-Philosophicus*. This exhibition draws connections between Wittgenstein's logical syntax, Immanuel Kant's schemata of pure understanding—where the mind generates raw sensory syntax and quotients it under cognitive concepts—and F. William Lawvere's category-theoretic foundations of physics and logic, demonstrating that the foundations of logic and physics are built upon algebraic presentations and adjunctions.",
      exercises: "1. Let $X = \\{x\\}$ and let $\\Sigma = \\{\\cdot\\}$ be a signature containing a single binary operation. Construct the free algebra $F(X)$ of binary trees. Let $R = \\{(x \\cdot x, x)\\}$. Formulate the quotient algebra $F(X)/\\langle R \\rangle$ and verify algebraically that it is isomorphic to the trivial single-element algebra.\n2. Prove that the coequalizer of a parallel pair in the category of monoids exists by explicitly constructing the congruence relation generated by a relation $R \\subseteq M \\times M$ and proving its universal property."
    },
    ja: {
      narrative: "存在論的サイクルへようこそ。数学はその最も深い存在論的土台において、静的な数や図形の学問ではなく、二つの根源的な認知操作、すなわち「自由生成（Free Generation）」と「商化（Quotienting）」の間の動的で周期的な対話です。人間はまず、一切の制約なしに生の記号や項、構文木を空間に投影します。これが純粋な構文の創造である「自由生成」です。次に、これらの項を方程式（関係式）のもとに折りたたみ、同一視し、崩壊させることで意味論を与え、現実の経験へとマッピングします。これが「商化」です。このループは構文と意味論の基本サイクルであり、いかにして無限の構造的ポテンシャルが機能的な意味へと束ねられるかを示しています。",
      rigor: "形式的には、このサイクルは生成元と関係式による代数系の表示としてモデル化されます。生の要素の集合 $X$ と演算のシグネチャ $\\Sigma$ から自由 $\\Sigma$-代数 $F(X)$ を構成し、同値関係を生成する関係式の集合 $R \\subseteq F(X) \\times F(X)$ を定めます。商構造 $F(X)/\\langle R \\rangle$ は、これらの関係式を満たす「初期」代数構造です。圏論的には、これは $\\Sigma$-代数の圏における、関係 $R$ の射影写像を拡張した準同型写像の並行対 $p_1, p_2: F(R) \\rightrightarrows F(X)$ のコイコライザー（余等化子）として定式化されます。商写像 $\\pi: F(X) \\to F(X)/\\langle R \\rangle$ はコイコライザー射であり、関係式を満たす最小の代数構造へと無限の自由構文を折りたたみます。",
      history: "「私の言語の限界は、私の世界の限界を意味する」 — ルートヴィヒ・ウィトゲンシュタイン『論理哲学論考』。本展示は、ウィトゲンシュタインの論理的構文論、イマヌエル・カントの純粋悟性概念（脳が生の感覚的構文を生成し、悟性概念の下で商化する図式論）、そしてウィリアム・ローヴェアによる物理と論理の圏論的基礎づけを結びつけ、数学の基礎が代数的表示と随伴の上に築かれていることを示します。",
      exercises: "1. $X = \\{x\\}$ とし、単一の二項演算 $\\cdot$ を持つシグネチャ $\\Sigma = \\{\\cdot\\}$ を考える。二分木の自由代数 $F(X)$ を構成し、関係式 $R = \\{(x \\cdot x, x)\\}$ に対する商代数 $F(X)/\\langle R \\rangle$ が1元からなる自明な代数と同型であることを代数的に確かめよ。\n2. モノイドの圏において、任意の射の並行対のコイコライザーが存在することを示すため、関係 $R \\subseteq M \\times M$ から生成される合同関係を具体的に構成し、その普遍性を証明せよ。"
    }
  },
  2: {
    id: 2,
    nameEn: "Hall II: Notches & Cardinality (Lebombo Bone)",
    nameJa: "第II室：ノッチと基数（レボンボ骨）",
    thesisEn: "Free generation of tally marks vs. Quotienting by bijection equivalence classes to form Cardinal Numbers.",
    thesisJa: "刻み目（タリカウンター）の自由生成と、基数を形成するための全単射同値類による商化。",
    image: "/images/lebombo_bone.jpg",
    imageAlt: "Lebombo Bone notches with lunar alignments",
    en: {
      narrative: "A million years ago, our ancestors carved notches on the Lebombo bone. The act of cutting tally marks I, II, III freely is the free generation of syntax, representing absolute freedom and structural potential. But raw marks are useless without a contract. By grouping these notches into equivalent packets (establishing a bijection to a herd of sheep or cycles of the moon) and quotienting by the relation of equipotence, humanity discovered cardinality. The number '5' is not a physical object; it is the quotient class of all tally marks that can be put in one-to-one correspondence.",
      rigor: "Let $\\mathcal{S}et_{\\text{fin}}$ be the category of finite sets. The free generation step corresponds to constructing finite ordinals in ZFC. The quotienting step partitions the class of finite sets under the equivalence relation of equipotence: $A \\sim B \\iff \\exists f: A \\to B$ which is bijective. In category theory, this is formalized by passing to the skeleton of the category. The skeleton $\\text{sk}(\\mathcal{S}et_{\\text{fin}})$ has objects that are finite ordinals $[n] = \\{0, 1, \\dots, n-1\\}$, representing $\\mathbb{N}_0$. Cardinality is the equivalence class of objects under isomorphism, and the cardinality map is the canonical skeletal functor from the core groupoid of finite sets to $\\mathbb{N}_0$.",
      history: "The Lebombo Bone (c. 35,000 BCE), discovered in eSwatini, contains 29 distinct notches carved into a baboon's fibula. While each individual notch is a free generator (syntax), mapping the 29-notch sequence to the lunar cycle represents a quotient relation (semantics), folding raw notches into a functional base-29 calendar register. This represents one of humanity's earliest cognitive steps from free symbol generation to relational meaning.",
      exercises: "1. Define a skeleton category $\\text{sk}(\\mathcal{S}et_{\\text{fin}})$ of the category of finite sets. Prove that it is equivalent as a category to $\\mathcal{S}et_{\\text{fin}}$ and that its set of objects is isomorphic to $\\mathbb{N}_0$, where each natural number $n$ is represented by the finite ordinal $[n] = \\{0, 1, \\dots, n-1\\}$.\n2. Prove that the relation of equipotence (isomorphism in $Set$) is an equivalence relation on sets. Show how Scott's trick can be used in ZFC to define cardinal numbers as sets without violating class containment."
    },
    ja: {
      narrative: "数万年前、人類の祖先はレボンボ骨に刻み目を刻みました。ルールなしに刻み目 I, II, III を無数に刻む行為は、純粋な記号構文の「自由生成」であり、無限の表現可能性を意味します。しかし、ただの刻み目だけでは意味をなしません。刻み目を特定の束に対応させ、羊の群れや月の周期と「一対一の対応（写像）」を作り、対等（全単射の存在）という関係式で「商化」することで、人類は基数（カルディナリティ）を発見しました。数「5」とは物理的な実体ではなく、一対一対応するすべてのノッチの「商集合（同値類）」なのです。",
      rigor: "有限集合の圏を $\\mathcal{S}et_{\\text{fin}}$ とする。自由生成ステップはZFCにおける有限順序数の構成に対応する。商化ステップは、対等（全単射の存在）という同値関係 $A \\sim B \\iff \\exists f: A \\to B$ による有限集合全体のクラスの分割である。圏論的には、これは圏の骨格（Skeleton）への移行として定式化される。骨格 $\\text{sk}(\\mathcal{S}et_{\\text{fin}})$ の対象は有限順序数 $[n] = \\{0, 1, \\dots, n-1\\}$ であり、これは自然数全体の集合 $\\mathbb{N}_0$ に対応する。基数とは同型写像に関する対象の同値類であり、基数写像は有限集合のコア亜群（同型射のみからなる部分圏）から $\\mathbb{N}_0$ への正準骨格関手である。",
      history: "エスワティニで発見されたレボンボ骨（紀元前約35,000年）には、ヒヒの腓骨に29個の個別の刻み目が刻まれています。個々の刻み目は単なる「自由生成（構文）」ですが、29個の刻み目を「月の満ち欠け（太陰周期）」にマッピングする行為は「商関係（意味論）」であり、生の刻み目をカレンダー登録という機能的な構造へと折りたたんでいます。これは人類最初の認知的な記号商化プロセスです。",
      exercises: "1. 有限集合の圏 $\\mathcal{S}et_{\\text{fin}}$ の骨格圏 $\\text{sk}(\\mathcal{S}et_{\\text{fin}})$ を定義せよ。これが $\\mathcal{S}et_{\\text{fin}}$ と圏同値であること、およびその対象の集合が、各自然数 $n$ を有限順序数 $[n] = \\{0, 1, \\dots, n-1\\}$ に対応させることで $\\mathbb{N}_0$ と同型になることを証明せよ。\n2. 集合間の対等関係（$Set$における同型関係）が同値関係であることを示せ。また、ZFCにおいてクラスの帰属関係の公理に矛盾することなく基数を集合として定義するために、スコットのトリック（Scott's trick）がどのように用いられるか説明せよ。"
    }
  },
  3: {
    id: 3,
    nameEn: "Hall III: Clay Tokens & Accounting (Ancient Sumeria)",
    nameJa: "第III室：粘土トークンと会計（古代シュメール）",
    thesisEn: "Free generation of clay tokens vs. Quotienting by contract agreements to define asset ownership.",
    thesisJa: "粘土トークンの自由生成と、資産所有権を定義するための契約合意による商化。",
    image: "/images/sumerian_tokens.jpg",
    imageAlt: "Sumerian clay tokens and clay bullae envelopes",
    en: {
      narrative: "In ancient Mesopotamia, trade required trust. Merchants created clay tokens shaped as spheres, cones, and cylinders to represent sheep, grain, or oil. Generating these physical tokens is free syntax. But tokens are easily counterfeited, stolen, or lost. To secure the contract, the Sumerians sealed the tokens inside hollow clay envelopes called 'bullae'. This sealed envelope established a physical quotient contract, locking raw elements into transaction equivalence. By stamping token shapes onto the outside of the bulla, humanity invented writing as a quotient projection.",
      rigor: "Let $T = \\{t_1, \\dots, t_k\\}$ be the set of token types. The free algebra $F(T)$ is the free commutative monoid $\\bigoplus_{t \\in T} \\mathbb{N}$ representing bundles of tokens. A transaction contract defines a congruence relation $\\sim$ on $F(T)$. Algebraically, if $v: F(T) \\to M$ is a monoid valuation homomorphism into a value monoid $M$ (e.g., $(\\mathbb{R}_{\\ge 0}, +, 0)$), then the congruence relation is the kernel of the homomorphism: $x \\sim_v y \\iff v(x) = v(y)$. The quotient monoid $F(T)/\\sim_v$ represents the algebra of semantic transaction values, and the bulla acts as the physical mechanism enforcing the quotient projection $\\pi: F(T) \\to F(T)/\\sim_v$.",
      history: "Sumerian clay bullae (c. 8000–3000 BCE) represent the first physical quotient contract. By sealing tokens inside, merchants ensured that neither party could alter the tokens without breaking the seal. The markings pressed onto the outer surface of the bulla eventually evolved into cuneiform writing, showing how quotient contracts generated the first formal written syntax, proving that writing was born to record quotient relations.",
      exercises: "1. Let $T = \\{s, o\\}$ where $s$ represents sheep and $o$ represents jars of oil. Let a contract impose the relation $3s \\sim 2o$. Construct the formal congruence relation $\\sim$ generated by this relation on the free commutative monoid $\\mathbb{N}s \\oplus \\mathbb{N}o$. Show algebraically whether $6s \\oplus 1o \\sim 2s \\oplus 3o$ holds.\n2. Prove that if $\\sim$ is a congruence relation on a monoid $M$, the quotient set $M/\\sim$ admits a unique monoid structure making the projection map $\\pi: M \\to M/\\sim$ a monoid homomorphism, and prove that $\\pi$ satisfies the universal property of quotient monoids."
    },
    ja: {
      narrative: "古代メソポタミアにおいて、交易には信頼が必要でした。商人は羊や穀物、油を表すために球体や円錐、円柱の形をした粘土のトークンを作りました。これらの物理的トークンを作る行為は「自由構文（自由生成）」です。しかし、トークンは偽造されたり紛失したりしやすいものでした。取引を保証するために、シュメール人は「ブッラ（Bullae）」と呼ばれる中空の粘土の封筒にトークンを封入しました。この封筒こそが最初の物理的「商契約」であり、生の要素を取引同値性へとロックしたのです。さらに、ブッラの表面に中のトークンの形を押し付けることで、人類は「文字」という商化された投影を発明しました。",
      rigor: "トークンの種類の集合を $T = \\{t_1, \\dots, t_k\\}$ とする。自由代数 $F(T)$ は、トークンの束を表す自由可換モノイド $\\bigoplus_{t \\in T} \\mathbb{N}$ である。取引契約は $F(T)$ 上の合同関係 $\\sim$ を定義する。代数的には、価値モノイド $M$ （例：$(\\mathbb{R}_{\\ge 0}, +, 0)$）への準同型写像 $v: F(T) \\to M$ が与えられたとき、合同関係は準同型写像の核（Kernel） $x \\sim_v y \\iff v(x) = v(y)$ として定義される。商モノイド $F(T)/\\sim_v$ は意味論的な取引価値の代数を表し、ブッラは商射影 $\\pi: F(T) \\to F(T)/\\sim_v$ を物理的に強制する仕組みとして機能する。",
      history: "シュメールの粘土製ブッラ（紀元前8000年〜3000年頃）は、人類最初の物理的な商化契約です。トークンを内部に密封することで、商人は封印を破ることなくトークンを変更できないようにしました。ブッラの外側にトークンを押し付けてつけたマークが、後の楔形文字へと進化し、商契約がいかにして文字構文を生み出したかを示しています。文字は商関係を記録するために誕生したのです。",
      exercises: "1. $T = \\{s, o\\}$ とする。ここで $s$ は羊、$o$ は油の瓶を表す。取引契約が $3s \\sim 2o$ という関係式を課すとする。自由可換モノイド $\\mathbb{N}s \\oplus \\mathbb{N}o$ 上でこの関係式から生成される合同関係 $\\sim$ を定式化せよ。これを用いて、$6s \\oplus 1o \\sim 2s \\oplus 3o$ が成り立つかどうかを代数的に判定せよ。\n2. モノイド $M$ 上の合同関係 $\\sim$ に対し、商集合 $M/\\sim$ の上に、自然な射影 $\\pi: M \\to M/\\sim$ がモノイド準同型写像となるような一意なモノイド構造が定義できることを示し、これが商モノイドの普遍性を満たすことを証明せよ。"
    }
  },
  4: {
    id: 4,
    nameEn: "Hall IV: Knotted Cord Paths (Inca Quipus)",
    nameJa: "第IV室：結縄（キープ）の経路（インカ帝国）",
    thesisEn: "Free loops of string vs. Quotienting by positional base-10 slots to store decimal values.",
    thesisJa: "紐（ストリング）の自由ループと、10進数値を格納するための位置的な10進法スロットによる商化。",
    image: "/images/inca_quipu.jpg",
    imageAlt: "Inca Quipu cords showing positional knots",
    en: {
      narrative: "Without a written alphabet, the Inca Empire managed vast agricultural registries and populations using the Quipu—a system of knotted cords. A main horizontal string holds dozens of hanging pendant cords. While a cord can support any number of knots in arbitrary arrangements (free loops of string), the Inca quotiented this free space by dividing each cord into strict positional tiers: units, tens, hundreds, and thousands. Position quotiented free loops into a base-10 relational register, proving that complex mathematics does not require paper or written symbols.",
      rigor: "Let the space of cord knot configurations be $C = \\bigoplus_{k \\in \\mathbb{N}_0} D$, where $D = \\{0, 1, \\dots, 9\\}$ is the set of possible knot counts at positional tier $k$ (corresponding to decimal positions). The evaluation mapping is the unique monoid homomorphism $\\text{eval}: C \\to \\mathbb{N}_0$ mapping $(a_k)_{k \\ge 0} \\mapsto \\sum_{k=0}^\\infty a_k 10^k$. The quotient relation $\\sim$ is the kernel of the evaluation map: $x \\sim y \\iff \\text{eval}(x) = \\text{eval}(y)$, partitioning the geometric configuration space $C$ into equivalence classes representing unique integers.",
      history: "Inca Quipus (c. 1400–1532 CE) served as the primary administrative and mathematical register of the Tawantinsuyu empire. Knotted string loops were freely generated and then quotiented by decimal position to store census, crop, and military data, proving that the human brain naturalized quotient spacing as a primary data structure before digital memory existed.",
      exercises: "1. Define the carry operation on the free monoid generated by digits $\\{0, \\dots, 9\\}$ as a congruence relation. Show that the quotient monoid is isomorphic to $(\\mathbb{N}_0, +, 0)$.\n2. Prove that the evaluation mapping $\\text{eval}: C \\to \\mathbb{N}_0$ is a surjective homomorphism of monoids, and construct its fibers as equivalence classes of cord configurations."
    },
    ja: {
      narrative: "文字を持たなかったインカ帝国は、結縄（キープ）と呼ばれる結び目のついたコードのシステムを使って、広大な農地や人口のデータを管理していました。主要な太い紐から、色とりどりの細い紐が数十本も垂れ下がっています。紐には任意の数や配置で自由に結び目（自由ループ）を作ることができますが、インカ人は各紐を「一、十、百、千」という厳格な「位置スロット」に分割することで商化しました。位置関係が自由な結び目を十進法の関係レジスタへと変えたのです。高度な数学に紙や記号が必須ではないことを証明しています。",
      rigor: "紐の上の結び目構成の空間を、各位置的階層 $k$ （10進法の桁に対応）における結び目の個数の集合 $D = \\{0, 1, \\dots, 9\\}$ の直和 $C = \\bigoplus_{k \\in \\mathbb{N}_0} D$ としてモデル化する。評価写像は、$(a_k)_{k \\ge 0} \\mapsto \\sum_{k=0}^\\infty a_k 10^k$ を割り当てる一意のモノイド準同型写像 $\\text{eval}: C \\to \\mathbb{N}_0$ である。商関係 $\\sim$ はこの評価写像の核 $x \\sim y \\iff \\text{eval}(x) = \\text{eval}(y)$ であり、幾何学的な構成空間 $C$ を一意な整数を表す同値類へと分割する。",
      history: "インカのキープ（西暦1400年〜1532年頃）は、タワンティンスーユ（インカ帝国）の主要な行政・数学レジスタでした。自由に結ばれた紐のループが、十進法の位置による商化契約によって人口調査、収穫量、軍事データを記録する手段となり、人類がデジタルメモリ以前に位置的商化を自然なデータ構造として用いていたことを物語っています。",
      exercises: "1. 記号の集合 $\\{0, \\dots, 9\\}$ から生成される自由モノイド上で、桁上げ操作（繰り上がり）を合同関係として定式化せよ。このとき商モノイドが $(\\mathbb{N}_0, +, 0)$ と同型であることを示せ。\n2. 評価写像 $\\text{eval}: C \\to \\mathbb{N}_0$ が全射モノイド準同型写像であることを証明し、そのファイバー（逆像）を紐の構成の同値類として構成せよ。"
    }
  },
  5: {
    id: 5,
    nameEn: "Hall V: Language Alphabet & Synonymy",
    nameJa: "第V室：言語の文字と同義性（フレーゲの意義と意味）",
    thesisEn: "Free monoid of string characters vs. Quotienting by synonymy equivalence classes to extract meaning.",
    thesisJa: "アルファベット文字列 of string characters の自由モノイドと、意味を抽出するための同義語同値類による商化。",
    en: {
      narrative: "With the alphabet, humanity unlocked infinite expression. Arranging letters freely to generate strings of text is the free generation of syntax. But stringing symbols together does not automatically create communication. Language requires a semantic quotient. When we group different strings under equivalence classes of synonyms or definitions (e.g., 'automobile' \\equiv 'car'), we partition the free syntactic monoid into semantic meaning, showing how language uses synonymy to collapse syntax into conceptual clarity.",
      rigor: "Let $\\Sigma$ be a finite alphabet. The free monoid $\\Sigma^*$ consists of all finite strings under concatenation. Given a language $L \\subseteq \\Sigma^*$, the syntactic congruence $\\sim_L$ is defined on $\\Sigma^*$ by: $u \\sim_L v \\iff \\forall x, y \\in \\Sigma^*, (xuy \\in L \\iff xvy \\in L)$. The quotient monoid $\\Sigma^*/\\sim_L$ is the syntactic monoid of $L$. It is finite if and only if $L$ is a regular language. Synonymy is modeled as this congruence, collapsing infinite syntax into semantic classes.",
      history: "This matches Gottlob Frege's distinction between *Sinn* (Sense/Syntax) and *Bedeutung* (Reference/Meaning) in his 1892 paper *Über Sinn und Bedeutung*. Frege argued that language freely generates infinite senses, but we quotient them by their real-world references to evaluate truth values, a foundational insight for analytical philosophy and compiler design.",
      exercises: "1. Let $\\Sigma = \\{a, b\\}$ and $L = \\{w \\in \\Sigma^* \\mid |w|_a \\equiv 0 \\pmod 2\\}$. Compute the equivalence classes of the syntactic congruence $\\sim_L$ and explicitly write down the multiplication table of the syntactic monoid $\\Sigma^*/\\sim_L$.\n2. Prove the Myhill-Nerode theorem's syntactic monoid version: a language $L \\subseteq \\Sigma^*$ is regular if and only if its syntactic congruence $\\sim_L$ has finite index. Show that $\\Sigma^*/\\sim_L$ is isomorphic to the transition monoid of the minimal DFA of $L$."
    },
    ja: {
      narrative: "文字と言葉を手に入れることで、人類は無限の表現力を獲得しました。アルファベットを自由に並べて文字列を生成する行為は、構文の「自由生成」です。しかし、文字列をただ並べるだけではコミュニケーションは生まれません。言語には意味論的な「商化」が必要です。異なる文字列を「同義語（シンタックスが違ってもセマンティクスが同じ）」として同じグループ（例：'自動車' ≡ '車'）に分類するとき、私たちは自由な文字列のモノイドを意味の世界へと商化しているのです。",
      rigor: "有限のアルファベットを $\\Sigma$ とし、その自由モノイドを $\\Sigma^*$ とする。言語 $L \\subseteq \\Sigma^*$ に対し、$\\Sigma^*$ 上の合同関係である構文合同（Syntactic Congruence） $\\sim_L$ を次のように定義する：$u \\sim_L v \\iff \\forall x, y \\in \\Sigma^*, (xuy \\in L \\iff xvy \\in L)$。商モノイド $\\Sigma^*/\\sim_L$ を $L$ の構文モノイドと呼ぶ。これが有限モノイドであることと、言語 $L$ が正規言語であることは同値である。同義性はこの合同関係としてモデル化され、無限の構文を意味論的クラスへと折りたたむ。",
      history: "これはゴットロープ・フレーゲの1892年の論文『意義と意味について』における「意義（Sinn/構文）」と「意味（Bedeutung/意味論）」の区別に一致します。フレーゲは、言語が無限の意義を自由生成し、それを現実の指示対象（リファレンス）によって商化することで真理値を評価すると主張しました。",
      exercises: "1. $\\Sigma = \\{a, b\\}$ とし、$L = \\{w \\in \\Sigma^* \\mid |w|_a \\equiv 0 \\pmod 2\\}$ （$a$が偶数個の文字列）とする。構文合同 $\\sim_L$ による同値類を計算し、構文モノイド $\\Sigma^*/\\sim_L$ の演算表（乗積表）を具体的に作成せよ。\n2. 構文モノイド版のマイヒル・ネローデの定理を証明せよ：言語 $L \\subseteq \\Sigma^*$ が正規言語であることと、構文合同 $\\sim_L$ の指数（同値類の数）が有限であることは同値である。また、$\\Sigma^*/\\sim_L$ が $L$ を受容する最小DFAの遷移モノイドと同型であることを示せ。"
    }
  },
  6: {
    id: 6,
    nameEn: "Hall VI: Deductive Reason & Classical Logic",
    nameJa: "第VI室：演繹的推論と古典論理（リンデンバウム・タルスキ）",
    thesisEn: "Free tree algebra of logic formulas vs. Quotienting by provable equivalence to form Heyting/Boolean algebras.",
    thesisJa: "論理式の自由木代数と、ヘイティング/ブール代数を形成するための証明可能な同値性による商化。",
    en: {
      narrative: "In logic, we build deductions. We generate sentences using atomic propositions and operators like AND, OR, NOT. This creates an infinite, free tree structure of syntactically valid propositions. However, many different sentences express the same logical truth. To build a mathematical algebra of logic, we must quotient these syntax trees by provable logical equivalence. Through this collapse, logic is transformed from raw syntax trees into algebraic lattices where we calculate truth.",
      rigor: "Let $F(X)$ be the free algebra generated by a set of propositional variables $X$ under the signature of logical connectives $\\Sigma = \\{\\land, \\lor, \\neg, \\top, \\bot\\}$. Given a logical theory $T$, we define the congruence relation $\\phi \\sim_T \\psi \\iff T \\vdash \\phi \\leftrightarrow \\psi$ (mutual provability in $T$). The quotient algebra $L(T) = F(X)/\\sim_T$ is the Lindenbaum-Tarski algebra. If $T$ is classical propositional logic, $L(T)$ is a Boolean algebra; if $T$ is intuitionistic propositional logic, $L(T)$ is a Heyting algebra. This quotients syntax trees into algebraic structures.",
      history: "Developed by Alfred Tarski and Adolf Lindenbaum in the 1930s, this quotient proved that logical deduction is equivalent to algebraic calculation in the quotient space. It represents the ultimate synthesis of syntactic proof and semantic truth, showing that reasoning is the quotient collapse of syntax.",
      exercises: "1. Prove that the relation $\\phi \\sim_T \\psi$ is indeed a congruence relation with respect to all operators in $\\Sigma = \\{\\land, \\lor, \\neg\\}$.\n2. Prove that the Lindenbaum-Tarski algebra $L(T)$ of a consistent theory $T$ contains at least two distinct equivalence classes (representing $\\top$ and $\\bot$), checking the complement and distributivity laws algebraically."
    },
    ja: {
      narrative: "論理学において、私たちは推論を組み立てます。命題変数と「かつ」「または」「ならば」といった論理演算子を使って論理式を組み立てる行為は、論理構文の「自由生成」であり、無限の論理式の木構造を生成します。しかし、一見異なる論理式でも、全く同じ論理的帰結を表すものが無数にあります。論理の代数学を構築するためには、これらの論理式を「証明可能な論理的同値性」によって商化し、折りたたまなければなりません。この崩壊によって、論理は代数的な構造へと変貌するのです。",
      rigor: "命題変数の集合 $X$ から、論理演算のシグネチャ $\\Sigma = \\{\\land, \\lor, \\neg, \\top, \\bot\\}$ の下で生成される自由代数を $F(X)$ とする。論理理論 $T$ に対し、合同関係 $\\phi \\sim_T \\psi \\iff T \\vdash \\phi \\leftrightarrow \\psi$ （$T$における相互証明可能性）を定義する。商代数 $L(T) = F(X)/\\sim_T$ はリンデンバウム・タルスキ代数（Lindenbaum-Tarski algebra）と呼ばれる。$T$ が古典命題論理であるとき $L(T)$ はブール代数となり、$T$ が直観主義命題論理であるとき $L(T)$ はヘイティング代数となる。これにより、構文木が代数構造へと商化される。",
      history: "1930年代にアルフレト・タルスキとアドルフ・リンデンバウムによって開発されたこの構成は、論理的な演繹が商空間における代数的な計算と同値であることを証明しました。構文的な「証明」と意味論的な「真理」を完璧に融合した金字塔です。",
      exercises: "1. 関係 $\\phi \\sim_T \\psi$ が、論理演算のシグネチャ $\\Sigma = \\{\\land, \\lor, \\neg\\}$ のすべての演算に関して合同関係であることを証明せよ。\n2. 整合的（矛盾のない）理論 $T$ のリンデンバウム・タルスキ代数 $L(T)$ が、少なくとも2つの異なる同値類（$\\top$ と $\\bot$）を持つことを証明し、相補律と分配律が代数的に成り立つことを確認せよ。"
    }
  },
  7: {
    id: 7,
    nameEn: "Hall VII: Textile Weaving & Patterns",
    nameJa: "第VII室：織物とパターン",
    thesisEn: "Free generation of warp and weft threads vs. Quotienting by weave intersection patterns to form fabric.",
    thesisJa: "経糸と緯糸の自由生成と、織布を形成するための交差パターンによる商化。",
    image: "/images/weaving_grid.jpg",
    imageAlt: "Weaving grid intersections showing thread quotients",
    en: {
      narrative: "Long before modern computers or algebra, textile weavers practiced topological gluing. A loom holds vertical warp threads and horizontal weft threads, which are initially independent (freely generated lines). But by interlacing them under a specific pattern (over-under-over), we force the threads to bind at grid intersections, quotienting independent threads into a single, continuous sheet of fabric. This shows how structural gluing quotients discrete dimensions into continuous manifolds.",
      rigor: "Let the warp threads be represented by $X = \\mathbb{R} \\times \\mathbb{Z} \\times \\{1\\}$ and the weft threads by $Y = \\mathbb{Z} \\times \\mathbb{R} \\times \\{0\\}$ in $\\mathbb{R}^3$. Let $W: \\mathbb{Z}^2 \\to \\{1, -1\\}$ be a periodic weaving matrix indicating whether the warp or weft thread is on top at the crossing $(i, j) \\in \\mathbb{Z}^2$. The fabric is the quotient space $M = (X \\sqcup Y)/\\sim$, where $\\sim$ identifies points $(i, y, 1)$ and $(x, j, 0)$ when $(x,y) = (i,j)$ and the threads are in contact. The periodic quotient of $M$ by the translation action of $G = \\mathbb{Z}^2$ yields a compact 2-dimensional manifold (a torus).",
      history: "Textile weaving is the oldest technology of continuous quotients. The punch-card system of the Jacquard Loom (1804) directly inspired Charles Babbage's Analytical Engine and Herman Hollerith's tabulating machines, proving that continuous topological quotients laid the path for binary computation and binary software.",
      exercises: "1. Define the translation action of the group $G = \\mathbb{Z}^2$ on the woven space $M = (X \\sqcup Y)/\\sim$ and prove that the quotient space $M/G$ is homeomorphic to a compact 2-dimensional manifold (the torus $\\mathbb{T}^2$).\n2. Prove that if the weaving matrix $W$ is alternating (plain weave, $W(i, j) = (-1)^{i+j}$), the resulting quotient topological space $M$ is connected."
    },
    ja: {
      narrative: "現代のコンピュータや代数学が登場するはるか昔、織物職人たちはトポロジー的な接着を実践していました。織機には垂直な「経糸（たていと）」と水平な「緯糸（よこいと）」が張られており、最初は別々に存在しています（自由生成された直線）。しかし、これらを特定のパターン（上・下・上）で交互に交差させることで、格子状の交点で糸同士を結びつけ、独立した糸を1枚の連続した「布（ファブリック）」へと商化します。これは、離散的な次元が接着によって連続的な多様体へと商化されるプロセスです。",
      rigor: "経糸を $\\mathbb{R}^3$ 内の $X = \\mathbb{R} \\times \\mathbb{Z} \\times \\{1\\}$、緯糸を $Y = \\mathbb{Z} \\times \\mathbb{R} \\times \\{0\\}$ とする。織り行列 $W: \\mathbb{Z}^2 \\to \\{1, -1\\}$ は交点 $(i, j) \\in \\mathbb{Z}^2$ において経糸と緯糸のどちらが上かを表す。織布は、経糸と緯糸が接触する点において $(i, y, 1) \\sim (x, j, 0)$ を同一視する商位相空間 $M = (X \\sqcup Y)/\\sim$ である。並進群 $G = \\mathbb{Z}^2$ の作用による $M$ の周期的な商空間 $M/G$ は、コンパクトな2次元多様体（トーラス）と同相になる。",
      history: "織物は、連続的な商構造を作る人類最古の技術です。ジャカード織機（1804年）のパンチカードシステムは、チャールズ・バベッジの解析機関やホレリスの集計機に直接的なインスピレーションを与え、連続的なトポロジーの商化がデジタル計算への道を切り拓いたことを示しています。",
      exercises: "1. 織布空間 $M = (X \\sqcup Y)/\\sim$ 上の並進群 $G = \\mathbb{Z}^2$ の作用を定義し、商空間 $M/G$ がコンパクト2次元多様体（2次元トーラス $\\mathbb{T}^2$）と同相であることを証明せよ。\n2. 織り行列 $W$ が交互（平織り、$W(i, j) = (-1)^{i+j}$）であるとき、得られる商位相空間 $M$ が連結空間であることを証明せよ。"
    }
  },
  8: {
    id: 8,
    nameEn: "Hall VIII: Origami Crease Patterns",
    nameJa: "第VIII室：折り紙の折れ線パターン",
    thesisEn: "Free flat paper surface vs. Quotienting by crease pattern fold-identifications to form 3D origami structures.",
    thesisJa: "平らな紙の自由表面と、3D折り紙構造を形成するための折れ線パターンによる商化。",
    en: {
      narrative: "Origami transforms flat paper into complex 3D shapes. We start with a flat sheet of paper, which has a simple 2D Euclidean topology (free space). By introducing a crease pattern (valleys and mountains) and folding along these lines, we identify separate points and segments of the paper, quotienting the flat space into a structured 3D object without stretching, tearing, or changing the local metric properties of the paper. This represents spatial quotienting through folding.",
      rigor: "Let $P = [0,1]^2$ be the unit square in $\\mathbb{R}^2$. A crease pattern is a planar graph $G = (V, E)$ on $P$. A fold map is a continuous piecewise isometry $f: P \\to \\mathbb{R}^3$ (with respect to the Euclidean metric on each face of $G$). Piecewise isometry means that $f$ preserves geodesic distances along paths within each face. The folded origami structure is the quotient space $P/\\sim_f$ where $x \\sim_f y \\iff f(x) = f(y)$.",
      history: "Folded geometry is found across nature, from leaf buds to insect wings. Modern origami mathematics, formalized by Toshikazu Kawasaki and Koryo Miura (the Miura fold), is used in space engineering to fold solar panels, and in biology to model how proteins fold, proving that flat syntactic sheets fold into complex semantic 3D functions.",
      exercises: "1. Formulate and prove Kawasaki's Theorem for a single-vertex flat-foldable crease pattern with angles $\\theta_1, \\theta_2, \\dots, \\theta_{2n}$ around the vertex. Show that $\\sum_{i=1}^n \\theta_{2i-1} = \\sum_{i=1}^n \\theta_{2i} = \\pi$ using the matrix representation of reflections.\n2. Prove that if $f: P \\to \\mathbb{R}^3$ is a continuous piecewise isometry, it is differentiable almost everywhere on $P$ and its derivative $Df$ (where defined) is an orthogonal matrix in $O(2, 3)$ representing local rotation without distortion."
    },
    ja: {
      narrative: "折り紙は平らな紙を複雑な3D形状へと変容させます。平らな正方形の紙は、シンプルな2次元ユークリッド空間（自由な空間）です。そこに折り目（山折りと谷折り）を刻み、線に沿って折ることで、紙の異なる点や辺同士を重ね合わせ、切ったり伸ばしたりすることなく、平らな空間を構造化された3Dオブジェクトへと商化します。これは折り畳みによる空間の商化を表現しています。",
      rigor: "単位正方形 $P = [0,1]^2 \\subset \\mathbb{R}^2$ とする。折り線パターンを $P$ 上の平面グラフ $G = (V, E)$ とする。折り畳み写像は、連続な区分的等長写像 $f: P \\to \\mathbb{R}^3$ である（各面においてユークリッド計量を保存する）。区分的等長写像とは、各面内のパスに沿った測地線距離が $f$ によって保存されることを意味する。折られた折り紙構造は、紙の異なる部分が重なり合う関係式 $x \\sim_f y \\iff f(x) = f(y)$ による商位相空間 $P/\\sim_f$ である。",
      history: "折られた幾何学は、植物の木の葉の芽から昆虫の羽の収納まで、自然界の至る所に見られます。川崎敏和や三浦公亮（ミウラ折り）らによって定式化された現代の折り紙数学は、宇宙工学における太陽電池パネルの展開や、バイオロジーにおけるタンパク質の折り畳みモデルに応用されています。平坦な構文シートが、折り畳みによって複雑な3次元意味論的機能へと昇華することを示しています。",
      exercises: "1. 頂点の周りの角度が $\\theta_1, \\theta_2, \\dots, \\theta_{2n}$ である単一頂点の平坦折り畳み可能折り線パターンに関する川崎の定理を定式化し、鏡映の行列表現を用いて $\\sum_{i=1}^n \\theta_{2i-1} = \\sum_{i=1}^n \\theta_{2i} = \\pi$ であることを証明せよ。\n2. 連続な区分的等長写像 $f: P \\to \\mathbb{R}^3$ が $P$ 上でほとんど至る所微分可能であり、その導関数 $Df$ が定義される点において $O(2, 3)$ 内の直交行列になることを証明せよ。"
    }
  },
  9: {
    id: 9,
    nameEn: "Hall IX: Quotient Topology (The Torus)",
    nameJa: "第IX室：商位相（トーラス境界接着）",
    thesisEn: "Free 2D coordinate square $[0,1]^2$ vs. Quotienting boundaries ($x \\sim x+1$, $y \\sim y+1$) to glue opposite edges and form a torus.",
    thesisJa: "自由な2次元座標正方形と、対向する辺を接着してトーラスを形成するための境界同値関係による商化。",
    en: {
      narrative: "In geometry, we transition from discrete dots to continuous space. We begin with a flat 2D sheet containing infinite points (free generation). By identifying its boundary points—gluing the top edge to the bottom edge, and then the left edge to the right edge—we fold the sheet into a cylinder, and ultimately a torus (quotienting). Shape is the semantic result of quotienting continuous coordinates, proving that space is structured by identifying boundaries.",
      rigor: "Let $X = [0,1]^2$ be the unit square in $\\mathbb{R}^2$ with the subspace topology. We define the equivalence relation $\\sim$ on $X$ by: $(x, 0) \\sim (x, 1)$ and $(0, y) \\sim (1, y)$ for all $x, y \\in [0,1]$. The quotient space $X/\\sim$ with the quotient topology is homeomorphic to the 2-torus $\\mathbb{T}^2 = S^1 \\times S^1$. Let $f: X \\to S^1 \\times S^1$ be defined by $f(x, y) = (e^{2\\pi i x}, e^{2\\pi i y})$. Since $f$ is a continuous surjection from the compact space $X$ to the Hausdorff space $S^1 \\times S^1$, and $a \\sim b \\iff f(a) = f(b)$, the induced map $\\bar{f}: X/\\sim \\to S^1 \\times S^1$ is a homeomorphism by the universal property of quotient topologies.",
      history: "Glued spaces appear historically in human weaving, basketry, and origami. In modern physics, general relativity and cosmic topology model the universe itself as a quotient space—where the syntax of flat spacetime is bent, glued, and curved by the distribution of mass-energy, converting coordinate syntax into physical shape.",
      exercises: "1. Let $\\sim_K$ be the equivalence relation on $X = [0,1]^2$ defined by $(x, 0) \\sim_K (x, 1)$ and $(0, y) \\sim_K (1, 1-y)$. Show that the quotient space $X/\\sim_K$ is the Klein bottle. Prove that it is a 2-dimensional manifold, and show it is non-orientable by computing the transition map determinants.\n2. Prove the compact-to-Hausdorff theorem: if $q: A \\to B$ is a continuous surjection from a compact space $A$ to a Hausdorff space $B$, then the induced map from the quotient space $\\bar{q}: A/\\sim \\to B$ is a homeomorphism."
    },
    ja: {
      narrative: "幾何学において、私たちは離散的な点から連続的な空間へと移行します。まず、無限の点を含む平らな2次元の正方形シートを用意します（自由生成）。そのシートの境界点同士を接着（上部と下部、次に左側と右側を同一視）することにより、円柱、そして最終的にはトーラス（ドーナツ型）へと折りたたみます（商化）。幾何学的な「図形」とは、連続的な座標を商化することによって生まれる意味論的結果なのです。",
      rigor: "単位正方形 $X = [0,1]^2 \\subset \\mathbb{R}^2$ （部分空間位相を備える）に対し、同値関係 $(x, 0) \\sim (x, 1)$ および $(0, y) \\sim (1, y)$ を定義する。商位相空間 $X/\\sim$ は2次元トーラス $\\mathbb{T}^2 = S^1 \\times S^1$ と同相である。写像 $f: X \\to S^1 \\times S^1$ を $f(x, y) = (e^{2\\pi i x}, e^{2\\pi i y})$ で定義すると、これはコンパクト空間 $X$ からハウスドルフ空間 $S^1 \\times S^1$ への連続全射であり、かつ $a \\sim b \\iff f(a) = f(b)$ が成り立つため、商位相の普遍性により、誘導される写像 $\\bar{f}: X/\\sim \\to S^1 \\times S^1$ は同相写像となる。",
      history: "接着された空間は、歴史的に機織り、籠編み、および折り紙などの技術に現れます。現代の一般相対性理論や宇宙トポロジーは、宇宙そのものを商空間としてモデル化します。質量分布という関係式によって、平坦な時空座標の構文が曲げられ、接着され、物理的な「形」へと変換されているのです。",
      exercises: "1. 単位正方形 $X = [0,1]^2$ 上の同値関係を $(x, 0) \\sim_K (x, 1)$ および $(0, y) \\sim_K (1, 1-y)$ で定義する。商空間 $X/\\sim_K$ がクラインの壺であることを示し、これが2次元多様体であることを証明せよ。また、座標変換写像のヤコビ行列の行列式を計算することで、これが向き付け不可能であることを示せ。\n2. コンパクトからハウスドルフへの定理を証明せよ：コンパクト空間 $A$ からハウスドルフ空間 $B$ への連続全射 $q: A \\to B$ が与えられたとき、商空間から誘導される写像 $\\bar{q}: A/\\sim \\to B$ は同相写像である。"
    }
  },
  10: {
    id: 10,
    nameEn: "Hall X: Projective Geometry",
    nameJa: "第X室：射影幾何学（実射影平面）",
    thesisEn: "Free points on a sphere $S^n$ vs. Quotienting by antipodal identification ($x \\sim -x$) to create the projective plane $\\mathbb{RP}^n$.",
    thesisJa: "球面上の自由点と、実射影平面を生成するための対蹠点同一視（$x \\sim -x$）による商化。",
    en: {
      narrative: "Projective geometry is the geometry of sight and perspective. Consider a sphere in 3D space, representing all possible directions of rays of light. If we declare that opposite points (antipodal points) are mathematically identical, we project the sphere into a new non-orientable topological space: the Real Projective Plane. By quotienting out the direction of lines through the origin, we construct the foundation of perspective, showing that human vision naturally quotients depth to construct flat image semantics.",
      rigor: "Let $S^n = \\{x \\in \\mathbb{R}^{n+1} \\mid \\|x\\| = 1\\}$ be the $n$-sphere. The equivalence relation is $x \\sim y \\iff x = \\pm y$ (antipodal identification), which is the orbit relation of the action of the group $\\mathbb{Z}_2 = \\{1, -1\\}$ on $S^n$. The quotient space $\\mathbb{RP}^n = S^n / \\sim$ is the real projective space. Geometrically, this is homeomorphic to the quotient space of $\\mathbb{R}^{n+1} \\setminus \\{0\\}$ by the scale action of the multiplicative group $\\mathbb{R}^* = \\mathbb{R} \\setminus \\{0\\}$. We show that $\\mathbb{RP}^n$ is a smooth manifold of dimension $n$ with atlas $U_i = \\{[x_0 : \\dots : x_n] \\mid x_i \\neq 0\\}$ and chart maps $\\phi_i: U_i \\to \\mathbb{R}^n$ mapping $[x_0 : \\dots : x_n] \\mapsto (x_0/x_i, \\dots, \\widehat{x_i/x_i}, \\dots, x_n/x_i)$.",
      history: "Born in the Renaissance when artists like Filippo Brunelleschi and Leon Battista Alberti formalized perspective drawing. Projective space proved that parallel lines 'meet' at infinity by quotienting out Euclidean parallel constraints, showing how the constraints of perspective generate a new coordinate syntax.",
      exercises: "1. Compute the transition maps $\\phi_j \\circ \\phi_i^{-1}$ for the standard atlas on $\\mathbb{RP}^n$, and show that they are smooth ($C^\\infty$) maps from $\\mathbb{R}^n \\setminus \\{x_j = 0\\}$ to itself.\n2. Prove that the canonical projection map $q: S^n \\to \\mathbb{RP}^n$ is a two-sheeted covering map and a local diffeomorphism."
    },
    ja: {
      narrative: "射影幾何学は、遠近法と視野の幾何学です。すべての光線の方向を表す3次元空間の球面を考えます。球面上にある、互いに正反対の位置にある点（対蹠点）同士を「完全に同じ点」として接着すると、実射影平面という新しいトポロジー空間が生まれます。原点を通る直線の方向性を「商化」して抽出することで、射影幾何学の基礎が構築されます。これは人間の視覚システムが奥行きを商化し、平坦な画像のセマンティクスを構築する仕組みそのものです。",
      rigor: "$n$次元球面 $S^n = \\{x \\in \\mathbb{R}^{n+1} \\mid \\|x\\| = 1\\}$ に対し、同値関係 $x \\sim y \\iff x = \\pm y$ （対蹠点同一視）を定義する。これは群 $\\mathbb{Z}_2 = \\{1, -1\\}$ の $S^n$ 上の作用による軌道関係である。商位相空間 $\\mathbb{RP}^n = S^n / \\sim$ は実射影空間である。幾何学的には、これは $\\mathbb{R}^{n+1} \\setminus \\{0\\}$ を乗法群 $\\mathbb{R}^* = \\mathbb{R} \\setminus \\{0\\}$ のスケール作用で割った商空間と同相である。$\\mathbb{RP}^n$ は、チャート $U_i = \\{[x_0 : \\dots : x_n] \\mid x_i \\neq 0\\}$ と写像 $\\phi_i: U_i \\to \\mathbb{R}^n$ （$x_i$ で割って $i$ 番目の成分を除く）からなるアトラスによって $n$ 次元滑らか多様体となる。",
      history: "ルネサンス期にフィリッポ・ブルネレスキやレオン・バティスタ・アルベルティが透視図法を定式化したことに始まります。射影空間は、並行な直線が無限遠点で交わることを示し、ユークリッドの平行線公理の制約を商化によって乗り越え、透視投影の制約が新しい座標構文を生み出すことを示しました。",
      exercises: "1. $\\mathbb{RP}^n$ の標準アトラスに関する座標変換写像 $\\phi_j \\circ \\phi_i^{-1}$ を計算し、それらが $\\mathbb{R}^n \\setminus \\{x_j = 0\\}$ 上の滑らかな（$C^\\infty$級）写像であることを示せ。\n2. 正準射影写像 $q: S^n \\to \\mathbb{RP}^n$ が、2葉の被覆写像（covering map）であり、かつ局所微分同相写像（local diffeomorphism）であることを証明せよ。"
    }
  }
};
